package com.opentravelsoft.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "tbl_group", catalog = "tourismwork_db")
public class Group implements java.io.Serializable {

  private int groupId;
  private Group parent;
  private String dptCn;
  private String fullName;
  private String linkman;
  private String tel;
  private String fax;
  private Set<Group> children = new HashSet<Group>(0);
  private Set<Employee> employees = new HashSet<Employee>(0);

  public Group() {
  }

  public Group(int groupId, String dptCn) {
    this.groupId = groupId;
    this.dptCn = dptCn;
  }

  public Group(int groupId, Group group, String dptCn, String fullName,
      String linkman, String tel, String fax, Set<Group> groups,
      Set<Employee> employees) {
    this.groupId = groupId;
    this.parent = group;
    this.dptCn = dptCn;
    this.fullName = fullName;
    this.linkman = linkman;
    this.tel = tel;
    this.fax = fax;
    this.children = groups;
    this.employees = employees;
  }

  @Id
  @Column(name = "GROUP_ID", unique = true, nullable = false)
  public int getGroupId() {
    return this.groupId;
  }

  public void setGroupId(int groupId) {
    this.groupId = groupId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "PARENT_ID")
  public Group getParent() {
    return parent;
  }

  public void setParent(Group parent) {
    this.parent = parent;
  }

  @Column(name = "DPT_CN", nullable = false, length = 20)
  public String getDptCn() {
    return this.dptCn;
  }

  public void setDptCn(String dptCn) {
    this.dptCn = dptCn;
  }

  @Column(name = "FULL_NAME", length = 60)
  public String getFullName() {
    return this.fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  @Column(name = "LINKMAN", length = 20)
  public String getLinkman() {
    return this.linkman;
  }

  public void setLinkman(String linkman) {
    this.linkman = linkman;
  }

  @Column(name = "TEL", length = 40)
  public String getTel() {
    return this.tel;
  }

  public void setTel(String tel) {
    this.tel = tel;
  }

  @Column(name = "FAX", length = 40)
  public String getFax() {
    return this.fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
  public Set<Group> getChildren() {
    return children;
  }

  public void setChildren(Set<Group> children) {
    this.children = children;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
  public Set<Employee> getEmployees() {
    return this.employees;
  }

  public void setEmployees(Set<Employee> employees) {
    this.employees = employees;
  }

  private String name;

  /** 联系人 */
  private String contact;

  private String phone;

  public String getName() {
    return name;
  }

  public void addChildren(Group child) {
    children.add(child);
  }

  public String getContact() {
    return contact;
  }

  public void setContact(String contact) {
    this.contact = contact;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public void setName(String name) {
    this.name = name;
  }

  public int compareTo(Group o) {
    if (this.groupId == o.getGroupId())
      return 0;
    else
      return 1;
  }

}
