package com.opentravelsoft.entity;

import java.util.Date;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TourNoticeFile generated by hbm2java
 */
@Entity
@Table(name = "tbl_tournotice_file", catalog = "tourismwork_db")
public class TourNoticeFile implements java.io.Serializable {

  private Integer fileId;
  private String tourNo;
  private String planNo;
  private String dptCd;
  private String fileName;
  private String filePath;
  private Integer fileSize;
  private Date overdue;
  private Character del;
  private String note;
  private Date created;
  private Integer createdby;

  public TourNoticeFile() {
  }

  public TourNoticeFile(String tourNo, String filename, String filepath) {
    this.tourNo = tourNo;
    this.fileName = filename;
    this.filePath = filepath;
  }

  public TourNoticeFile(String tourNo, String planNo, String dptCd,
      String filename, String filepath, Integer filesize, Date overdue,
      Character del, String note, Date created, Integer createdby) {
    this.tourNo = tourNo;
    this.planNo = planNo;
    this.dptCd = dptCd;
    this.fileName = filename;
    this.filePath = filepath;
    this.fileSize = filesize;
    this.overdue = overdue;
    this.del = del;
    this.note = note;
    this.created = created;
    this.createdby = createdby;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "ID", unique = true, nullable = false)
  public Integer getFileId() {
    return this.fileId;
  }

  public void setFileId(Integer id) {
    this.fileId = id;
  }

  @Column(name = "TOUR_NO", nullable = false, length = 100)
  public String getTourNo() {
    return this.tourNo;
  }

  public void setTourNo(String tourNo) {
    this.tourNo = tourNo;
  }

  @Column(name = "PLAN_NO", length = 20)
  public String getPlanNo() {
    return this.planNo;
  }

  public void setPlanNo(String planNo) {
    this.planNo = planNo;
  }

  @Column(name = "DPT_CD", length = 4)
  public String getDptCd() {
    return this.dptCd;
  }

  public void setDptCd(String dptCd) {
    this.dptCd = dptCd;
  }

  @Column(name = "FILENAME", nullable = false, length = 120)
  public String getFileName() {
    return this.fileName;
  }

  public void setFileName(String filename) {
    this.fileName = filename;
  }

  @Column(name = "FILEPATH", nullable = false, length = 120)
  public String getFilePath() {
    return this.filePath;
  }

  public void setFilePath(String filepath) {
    this.filePath = filepath;
  }

  @Column(name = "FILESIZE")
  public Integer getFileSize() {
    return this.fileSize;
  }

  public void setFileSize(Integer filesize) {
    this.fileSize = filesize;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "OVERDUE", length = 19)
  public Date getOverdue() {
    return this.overdue;
  }

  public void setOverdue(Date overdue) {
    this.overdue = overdue;
  }

  @Column(name = "DEL", length = 1)
  public Character getDel() {
    return this.del;
  }

  public void setDel(Character del) {
    this.del = del;
  }

  @Column(name = "NOTE", length = 60)
  public String getNote() {
    return this.note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "CREATED", length = 19)
  public Date getCreated() {
    return this.created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  @Column(name = "CREATEDBY")
  public Integer getCreatedby() {
    return this.createdby;
  }

  public void setCreatedby(Integer createdby) {
    this.createdby = createdby;
  }

  private String groupId;

  private Long operator;

  private String delKey;

  public String getDptNo() {
    return groupId;
  }

  public void setDptNo(String groupId) {
    this.groupId = groupId;
  }

  public Long getOperator() {
    return operator;
  }

  public void setOperator(Long operator) {
    this.operator = operator;
  }

  public String getDelKey() {
    return delKey;
  }

  public void setDelKey(String delKey) {
    this.delKey = delKey;
  }

}
