package com.opentravelsoft.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisaHelp generated by hbm2java
 */
@Entity
@Table(name = "tbl_visa", catalog = "tourismwork_db")
public class VisaHelp implements java.io.Serializable {

  private String recNo;
  /** 国家/地区 CODE */
  private String country;
  /** 项目 */
  private String subject;
  
  private BigDecimal price1;
  
  private BigDecimal price2;
  private BigDecimal cost;
  /** 单位 */
  private String unit;
  private Date SDate;
  private Date EDate;
  private String note;
  private Integer canQuick;
  private Character visaKind;
  private String stayDays;
  private String transactDays;
  private Integer isOpen;
  private Character opKey;
  private Integer opUser;
  private Date opDate;

  public VisaHelp() {
  }

  public VisaHelp(String recNo, Date opDate) {
    this.recNo = recNo;
    this.opDate = opDate;
  }

  public VisaHelp(String recNo, String country, String subject,
      BigDecimal price1, BigDecimal price2, BigDecimal cost, String unit,
      Date SDate, Date EDate, String note, Integer canQuick,
      Character visaKind, String stayDays, String transactDays, Integer isOpen,
      Character opKey, Integer opUser, Date opDate) {
    this.recNo = recNo;
    this.country = country;
    this.subject = subject;
    this.price1 = price1;
    this.price2 = price2;
    this.cost = cost;
    this.unit = unit;
    this.SDate = SDate;
    this.EDate = EDate;
    this.note = note;
    this.canQuick = canQuick;
    this.visaKind = visaKind;
    this.stayDays = stayDays;
    this.transactDays = transactDays;
    this.isOpen = isOpen;
    this.opKey = opKey;
    this.opUser = opUser;
    this.opDate = opDate;
  }

  @Id
  @Column(name = "REC_NO", unique = true, nullable = false, length = 10)
  public String getRecNo() {
    return this.recNo;
  }

  public void setRecNo(String recNo) {
    this.recNo = recNo;
  }

  @Column(name = "COUNTRY", length = 2)
  public String getCountry() {
    return this.country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  @Column(name = "SUBJECT", length = 200)
  public String getSubject() {
    return this.subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  @Column(name = "PRICE1", precision = 9)
  public BigDecimal getPrice1() {
    return this.price1;
  }

  public void setPrice1(BigDecimal price1) {
    this.price1 = price1;
  }

  @Column(name = "PRICE2", precision = 9)
  public BigDecimal getPrice2() {
    return this.price2;
  }

  public void setPrice2(BigDecimal price2) {
    this.price2 = price2;
  }

  @Column(name = "COST", precision = 9)
  public BigDecimal getCost() {
    return this.cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }

  @Column(name = "UNIT", length = 16)
  public String getUnit() {
    return this.unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "S_DATE", length = 19)
  public Date getSDate() {
    return this.SDate;
  }

  public void setSDate(Date SDate) {
    this.SDate = SDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "E_DATE", length = 19)
  public Date getEDate() {
    return this.EDate;
  }

  public void setEDate(Date EDate) {
    this.EDate = EDate;
  }

  @Column(name = "NOTE", length = 3000)
  public String getNote() {
    return this.note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  @Column(name = "CAN_QUICK")
  public Integer getCanQuick() {
    return this.canQuick;
  }

  public void setCanQuick(Integer canQuick) {
    this.canQuick = canQuick;
  }

  @Column(name = "VISA_KIND", length = 1)
  public Character getVisaKind() {
    return this.visaKind;
  }

  public void setVisaKind(Character visaKind) {
    this.visaKind = visaKind;
  }

  @Column(name = "STAY_DAYS", length = 20)
  public String getStayDays() {
    return this.stayDays;
  }

  public void setStayDays(String stayDays) {
    this.stayDays = stayDays;
  }

  @Column(name = "TRANSACT_DAYS", length = 20)
  public String getTransactDays() {
    return this.transactDays;
  }

  public void setTransactDays(String transactDays) {
    this.transactDays = transactDays;
  }

  @Column(name = "IS_OPEN")
  public Integer getIsOpen() {
    return this.isOpen;
  }

  public void setIsOpen(Integer isOpen) {
    this.isOpen = isOpen;
  }

  @Column(name = "OP_KEY", length = 1)
  public Character getOpKey() {
    return this.opKey;
  }

  public void setOpKey(Character opKey) {
    this.opKey = opKey;
  }

  @Column(name = "OP_USER")
  public Integer getOpUser() {
    return this.opUser;
  }

  public void setOpUser(Integer opUser) {
    this.opUser = opUser;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "OP_DATE", nullable = false, length = 19)
  public Date getOpDate() {
    return this.opDate;
  }

  public void setOpDate(Date opDate) {
    this.opDate = opDate;
  }

  private String recordNo;


  /** 国家/地区名称 */
  private String cnName;

  /** 市场价（及直客价） */
  private double marketPrice;

  /** 同行价 */
  private double quotedPrice;

  /** 成本价 */
  private double costPrice;


  /** 开始有效日期 */
  private Date startDate;

  /** 终止有效日期 */
  private Date endDate;

  /** 条款内容 */
  private String note;

  /** 签证种类 */
  private String visaKind;

  /** 停留天数 */
  private String stayDays;

  /** 办理时间 */
  private String transactDays;

  /** 网站开放 */
  private Integer isOpen;

  /** 是否可以办理加急 */
  private Integer canQuick;

  /** 所须材料列表 */
  private List<VisaItem> items;

  /** 所须附件列表 */
  private List<VisaItem> fileItems;

  /** 直客价 */
  private Double price1;

  /** 同行价 */
  private Double price2;

  public VisaHelp() {
    country = "";
    subject = "";
    marketPrice = 0;
    quotedPrice = 0;
    costPrice = 0;
    unit = "";
    visaKind = "S";
    items = new ArrayList<VisaItem>();
    fileItems = new ArrayList<VisaItem>();
  }

  public String getRecNo() {
    return this.recNo;
  }

  public void setRecNo(String recNo) {
    this.recNo = recNo;
  }

  public Double getPrice1() {
    return this.price1;
  }

  public void setPrice1(Double price1) {
    this.price1 = price1;
  }

  public Double getPrice2() {
    return this.price2;
  }

  public void setPrice2(Double price2) {
    this.price2 = price2;
  }

  public Double getCost() {
    return this.cost;
  }

  public void setCost(Double cost) {
    this.cost = cost;
  }

  public Date getSDate() {
    return this.SDate;
  }

  public void setSDate(Date SDate) {
    this.SDate = SDate;
  }

  public Date getEDate() {
    return this.EDate;
  }

  public void setEDate(Date EDate) {
    this.EDate = EDate;
  }

  public String getOpKey() {
    return this.opKey;
  }

  public void setOpKey(String opKey) {
    this.opKey = opKey;
  }

  public Date getOpDate() {
    return this.opDate;
  }

  public void setOpDate(Date opDate) {
    this.opDate = opDate;
  }

  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public double getMarketPrice() {
    return marketPrice;
  }

  public void setMarketPrice(double marketPrice) {
    this.marketPrice = marketPrice;
  }

  public double getQuotedPrice() {
    return quotedPrice;
  }

  public void setQuotedPrice(double quotedPrice) {
    this.quotedPrice = quotedPrice;
  }

  public double getCostPrice() {
    return costPrice;
  }

  public void setCostPrice(double costPrice) {
    this.costPrice = costPrice;
  }

  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public String getSubject() {
    return subject;
  }

  public void setSubject(String item) {
    this.subject = item;
  }

  public Date getStartDate() {
    return startDate;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public Date getEndDate() {
    return endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public String getRecordNo() {
    return recordNo;
  }

  public void setRecordNo(String recordNo) {
    this.recordNo = recordNo;
  }

  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public String getCnName() {
    return cnName;
  }

  public void setCnName(String cnName) {
    this.cnName = cnName;
  }

  public Long getOpUser() {
    return opUser;
  }

  public void setOpUser(Long opUser) {
    this.opUser = opUser;
  }

  public List<VisaItem> getItems() {
    return items;
  }

  public void setItems(List<VisaItem> items) {
    this.items = items;
  }

  public String getVisaKind() {
    return visaKind;
  }

  public void setVisaKind(String visaKind) {
    this.visaKind = visaKind;
  }

  public String getStayDays() {
    return stayDays;
  }

  public void setStayDays(String stayDays) {
    this.stayDays = stayDays;
  }

  public String getTransactDays() {
    return transactDays;
  }

  public void setTransactDays(String transactDays) {
    this.transactDays = transactDays;
  }

  public Integer getIsOpen() {
    return isOpen;
  }

  public void setIsOpen(Integer isOpen) {
    this.isOpen = isOpen;
  }

  public List<VisaItem> getFileItems() {
    return fileItems;
  }

  public void setFileItems(List<VisaItem> fileItems) {
    this.fileItems = fileItems;
  }

  public Integer getCanQuick() {
    return canQuick;
  }

  public void setCanQuick(Integer canQuick) {
    this.canQuick = canQuick;
  }
}
