package com.opentravelsoft.entity.finance;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Income generated by hbm2java
 */
@Entity
@Table(name = "tbl_income", catalog = "tourismwork_db")
public class Income implements java.io.Serializable {

	private Integer incomeId;
	private int customerId;
	private Character payMode;
	private String dptNo;
	private String receiver;
	private String note;
	private BigDecimal amount;
	private Date incomeDate;
	private BigDecimal offsetAmount;
	private Date created;
	private Integer createdby;
	private Date updated;
	private Integer updatedby;
	private String bookingNo;
	private String useType;

	public Income() {
	}

	public Income(int customerId, Date updated, String bookingNo) {
		this.customerId = customerId;
		this.updated = updated;
		this.bookingNo = bookingNo;
	}

	public Income(int customerId, Character payMode, String dptNo,
			String receiver, String note, BigDecimal amount, Date incomeDate,
			BigDecimal offsetAmount, Date created, Integer createdby,
			Date updated, Integer updatedby, String bookingNo, String useType) {
		this.customerId = customerId;
		this.payMode = payMode;
		this.dptNo = dptNo;
		this.receiver = receiver;
		this.note = note;
		this.amount = amount;
		this.incomeDate = incomeDate;
		this.offsetAmount = offsetAmount;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
		this.bookingNo = bookingNo;
		this.useType = useType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INCOME_ID", unique = true, nullable = false)
	public Integer getIncomeId() {
		return this.incomeId;
	}

	public void setIncomeId(Integer incomeId) {
		this.incomeId = incomeId;
	}

	@Column(name = "CUSTOMER_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "PAY_MODE", length = 1)
	public Character getPayMode() {
		return this.payMode;
	}

	public void setPayMode(Character payMode) {
		this.payMode = payMode;
	}

	@Column(name = "DPT_NO", length = 6)
	public String getDptNo() {
		return this.dptNo;
	}

	public void setDptNo(String dptNo) {
		this.dptNo = dptNo;
	}

	@Column(name = "RECEIVER", length = 20)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "NOTE", length = 1000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "AMOUNT", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INCOME_DATE", length = 19)
	public Date getIncomeDate() {
		return this.incomeDate;
	}

	public void setIncomeDate(Date incomeDate) {
		this.incomeDate = incomeDate;
	}

	@Column(name = "OFFSET_AMOUNT", precision = 10)
	public BigDecimal getOffsetAmount() {
		return this.offsetAmount;
	}

	public void setOffsetAmount(BigDecimal offsetAmount) {
		this.offsetAmount = offsetAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "CREATEDBY")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "UPDATEDBY")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "BOOKING_NO", nullable = false, length = 20)
	public String getBookingNo() {
		return this.bookingNo;
	}

	public void setBookingNo(String bookingNo) {
		this.bookingNo = bookingNo;
	}

	@Column(name = "USE_TYPE", length = 20)
	public String getUseType() {
		return this.useType;
	}

	public void setUseType(String useType) {
		this.useType = useType;
	}

}
