package com.opentravelsoft.entity.finance;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reckoning generated by hbm2java
 */
@Entity
@Table(name = "tbl_reckoning", catalog = "tourismwork_db")
public class Reckoning implements java.io.Serializable {

	private Integer reckoningId;
	private String bookingNo;
	private int number;
	private char tourType;
	private String routeNote;
	private String description;
	private String remarks;
	private String contact;
	private String phone;
	private String fax;
	private Integer leaderAmt;
	private Character isprinted;
	private Date printed;
	private Integer printedCount;
	private Date created;
	private Integer createdby;
	private Date updated;
	private Integer updatedby;

	public Reckoning() {
	}

	public Reckoning(String bookingNo, int number, char tourType, Date updated) {
		this.bookingNo = bookingNo;
		this.number = number;
		this.tourType = tourType;
		this.updated = updated;
	}

	public Reckoning(String bookingNo, int number, char tourType,
			String routeNote, String description, String remarks,
			String contact, String phone, String fax, Integer leaderAmt,
			Character isprinted, Date printed, Integer printedCount,
			Date created, Integer createdby, Date updated, Integer updatedby) {
		this.bookingNo = bookingNo;
		this.number = number;
		this.tourType = tourType;
		this.routeNote = routeNote;
		this.description = description;
		this.remarks = remarks;
		this.contact = contact;
		this.phone = phone;
		this.fax = fax;
		this.leaderAmt = leaderAmt;
		this.isprinted = isprinted;
		this.printed = printed;
		this.printedCount = printedCount;
		this.created = created;
		this.createdby = createdby;
		this.updated = updated;
		this.updatedby = updatedby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RECKONING_ID", unique = true, nullable = false)
	public Integer getReckoningId() {
		return this.reckoningId;
	}

	public void setReckoningId(Integer reckoningId) {
		this.reckoningId = reckoningId;
	}

	@Column(name = "BOOKING_NO", nullable = false, length = 20)
	public String getBookingNo() {
		return this.bookingNo;
	}

	public void setBookingNo(String bookingNo) {
		this.bookingNo = bookingNo;
	}

	@Column(name = "NUMBER", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "TOUR_TYPE", nullable = false, length = 1)
	public char getTourType() {
		return this.tourType;
	}

	public void setTourType(char tourType) {
		this.tourType = tourType;
	}

	@Column(name = "ROUTE_NOTE", length = 1000)
	public String getRouteNote() {
		return this.routeNote;
	}

	public void setRouteNote(String routeNote) {
		this.routeNote = routeNote;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "CONTACT", length = 20)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "PHONE", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "LEADER_AMT")
	public Integer getLeaderAmt() {
		return this.leaderAmt;
	}

	public void setLeaderAmt(Integer leaderAmt) {
		this.leaderAmt = leaderAmt;
	}

	@Column(name = "ISPRINTED", length = 1)
	public Character getIsprinted() {
		return this.isprinted;
	}

	public void setIsprinted(Character isprinted) {
		this.isprinted = isprinted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRINTED", length = 19)
	public Date getPrinted() {
		return this.printed;
	}

	public void setPrinted(Date printed) {
		this.printed = printed;
	}

	@Column(name = "PRINTED_COUNT")
	public Integer getPrintedCount() {
		return this.printedCount;
	}

	public void setPrintedCount(Integer printedCount) {
		this.printedCount = printedCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "CREATEDBY")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "UPDATEDBY")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

}
