package com.opentravelsoft.hmodel;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblLineCountry generated by hbm2java
 */
@Entity
@Table(name = "tbl_line_country", catalog = "tourismwork_db")
public class TblLineCountry implements java.io.Serializable {

	private TblLineCountryId id;

	public TblLineCountry() {
	}

	public TblLineCountry(TblLineCountryId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lineNo", column = @Column(name = "LINE_NO", nullable = false, length = 8)),
			@AttributeOverride(name = "countryCd", column = @Column(name = "COUNTRY_CD", nullable = false, length = 2)) })
	public TblLineCountryId getId() {
		return this.id;
	}

	public void setId(TblLineCountryId id) {
		this.id = id;
	}

}
