package com.opentravelsoft.hmodel;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblTeamMembershipsId generated by hbm2java
 */
@Embeddable
public class TblTeamMembershipsId implements java.io.Serializable {

	private int teamId;
	private int userId;

	public TblTeamMembershipsId() {
	}

	public TblTeamMembershipsId(int teamId, int userId) {
		this.teamId = teamId;
		this.userId = userId;
	}

	@Column(name = "TEAM_ID", nullable = false)
	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblTeamMembershipsId))
			return false;
		TblTeamMembershipsId castOther = (TblTeamMembershipsId) other;

		return (this.getTeamId() == castOther.getTeamId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeamId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
