package com.opentravelsoft.hmodel;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import com.opentravelsoft.entity.Employee;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblTeamMemberships generated by hbm2java
 */
@Entity
@Table(name = "tbl_team_memberships", catalog = "tourismwork_db")
public class TblTeamMemberships implements java.io.Serializable {

	private TblTeamMembershipsId id;
	private Employee employee;

	public TblTeamMemberships() {
	}

	public TblTeamMemberships(TblTeamMembershipsId id, Employee employee) {
		this.id = id;
		this.employee = employee;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "teamId", column = @Column(name = "TEAM_ID", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)) })
	public TblTeamMembershipsId getId() {
		return this.id;
	}

	public void setId(TblTeamMembershipsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

}
