package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Airport generated by hbm2java
 */
@Entity
@Table(name = "tbl_airport", catalog = "tourismwork_db")
public class Airport implements java.io.Serializable {

	private String code;
	private City city;
	private String name;
	private String enName;
	private Byte isActive;

	public Airport() {
	}

	public Airport(String code) {
		this.code = code;
	}

	public Airport(String code, City city, String name, String enName,
			Byte isActive) {
		this.code = code;
		this.city = city;
		this.name = name;
		this.enName = enName;
		this.isActive = isActive;
	}

	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITY_ID")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "NAME", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EN_NAME", length = 50)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "IS_ACTIVE")
	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

}
