package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "tbl_booking", catalog = "tourismwork_db")
public class Booking implements java.io.Serializable {

	private String nameNo;
	private String planNo;
	private int teamId;
	private Integer assignedUserId;
	private int customerId;
	private String contact;
	private String tel;
	private Integer pax;
	private Integer confirmPax;
	private BigDecimal dbamt;
	private BigDecimal cramt;
	private String namekey;
	private String tourK1;
	private String delkey;
	private Integer opuser;
	private Date opTime;
	private Integer receive;
	private Date receiveDt;
	private Integer salesman;
	private String pactNo;
	private Character tourKey;
	private String remarks;
	private String cfmKey;
	private String invKey;
	private Integer invUser;
	private Date invDate;
	private String readKey;
	private Integer readUser;
	private Date readDate;
	private String planKey;
	private BigDecimal finalAmount;
	private Integer finalUser;
	private Date finalDate;
	private String finalNote;
	private String warrantFlag;
	private Integer warrantBy;
	private Date warrantDate;
	private BigDecimal warrantMoney;
	private Date lastPayDate;
	private String source;
	private String workflowId;
	private Character checkKey;
	private BigDecimal expAmt;
	private Character orderState;
	private Integer isAgreeon;
	private Integer memberId;
	private String lineNo;
	private String userName;
	private String fax;
	private String mobile;
	private String email;
	private Character productType;
	private Integer adult;
	private Integer child;
	private Integer roomNum;
	private Integer productState;
	private Integer state;
	private Date outDate;
	private Byte userType;
	private Byte bookingSource;
	private Byte isDelete;
	private Integer createdBy;
	private Date createdDate;
	private String createdByIp;
	private String modifiedByIp;
	private Byte isNeedInvoice;
	private String invoiceHead;
	private String invoinceContent;
	private Byte postWay;

	public Booking() {
	}

	public Booking(String nameNo, String planNo, int teamId, int customerId,
			String namekey, Date opTime) {
		this.nameNo = nameNo;
		this.planNo = planNo;
		this.teamId = teamId;
		this.customerId = customerId;
		this.namekey = namekey;
		this.opTime = opTime;
	}

	public Booking(String nameNo, String planNo, int teamId,
			Integer assignedUserId, int customerId, String contact, String tel,
			Integer pax, Integer confirmPax, BigDecimal dbamt,
			BigDecimal cramt, String namekey, String tourK1, String delkey,
			Integer opuser, Date opTime, Integer receive, Date receiveDt,
			Integer salesman, String pactNo, Character tourKey, String remarks,
			String cfmKey, String invKey, Integer invUser, Date invDate,
			String readKey, Integer readUser, Date readDate, String planKey,
			BigDecimal finalAmount, Integer finalUser, Date finalDate,
			String finalNote, String warrantFlag, Integer warrantBy,
			Date warrantDate, BigDecimal warrantMoney, Date lastPayDate,
			String source, String workflowId, Character checkKey,
			BigDecimal expAmt, Character orderState, Integer isAgreeon,
			Integer memberId, String lineNo, String userName, String fax,
			String mobile, String email, Character productType, Integer adult,
			Integer child, Integer roomNum, Integer productState,
			Integer state, Date outDate, Byte userType, Byte bookingSource,
			Byte isDelete, Integer createdBy, Date createdDate,
			String createdByIp, String modifiedByIp, Byte isNeedInvoice,
			String invoiceHead, String invoinceContent, Byte postWay) {
		this.nameNo = nameNo;
		this.planNo = planNo;
		this.teamId = teamId;
		this.assignedUserId = assignedUserId;
		this.customerId = customerId;
		this.contact = contact;
		this.tel = tel;
		this.pax = pax;
		this.confirmPax = confirmPax;
		this.dbamt = dbamt;
		this.cramt = cramt;
		this.namekey = namekey;
		this.tourK1 = tourK1;
		this.delkey = delkey;
		this.opuser = opuser;
		this.opTime = opTime;
		this.receive = receive;
		this.receiveDt = receiveDt;
		this.salesman = salesman;
		this.pactNo = pactNo;
		this.tourKey = tourKey;
		this.remarks = remarks;
		this.cfmKey = cfmKey;
		this.invKey = invKey;
		this.invUser = invUser;
		this.invDate = invDate;
		this.readKey = readKey;
		this.readUser = readUser;
		this.readDate = readDate;
		this.planKey = planKey;
		this.finalAmount = finalAmount;
		this.finalUser = finalUser;
		this.finalDate = finalDate;
		this.finalNote = finalNote;
		this.warrantFlag = warrantFlag;
		this.warrantBy = warrantBy;
		this.warrantDate = warrantDate;
		this.warrantMoney = warrantMoney;
		this.lastPayDate = lastPayDate;
		this.source = source;
		this.workflowId = workflowId;
		this.checkKey = checkKey;
		this.expAmt = expAmt;
		this.orderState = orderState;
		this.isAgreeon = isAgreeon;
		this.memberId = memberId;
		this.lineNo = lineNo;
		this.userName = userName;
		this.fax = fax;
		this.mobile = mobile;
		this.email = email;
		this.productType = productType;
		this.adult = adult;
		this.child = child;
		this.roomNum = roomNum;
		this.productState = productState;
		this.state = state;
		this.outDate = outDate;
		this.userType = userType;
		this.bookingSource = bookingSource;
		this.isDelete = isDelete;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.createdByIp = createdByIp;
		this.modifiedByIp = modifiedByIp;
		this.isNeedInvoice = isNeedInvoice;
		this.invoiceHead = invoiceHead;
		this.invoinceContent = invoinceContent;
		this.postWay = postWay;
	}

	@Id
	@Column(name = "NAME_NO", unique = true, nullable = false, length = 10)
	public String getNameNo() {
		return this.nameNo;
	}

	public void setNameNo(String nameNo) {
		this.nameNo = nameNo;
	}

	@Column(name = "PLAN_NO", nullable = false, length = 20)
	public String getPlanNo() {
		return this.planNo;
	}

	public void setPlanNo(String planNo) {
		this.planNo = planNo;
	}

	@Column(name = "TEAM_ID", nullable = false)
	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	@Column(name = "ASSIGNED_USER_ID")
	public Integer getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(Integer assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	@Column(name = "CUSTOMER_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CONTACT", length = 20)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "TEL", length = 60)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "PAX")
	public Integer getPax() {
		return this.pax;
	}

	public void setPax(Integer pax) {
		this.pax = pax;
	}

	@Column(name = "CONFIRM_PAX")
	public Integer getConfirmPax() {
		return this.confirmPax;
	}

	public void setConfirmPax(Integer confirmPax) {
		this.confirmPax = confirmPax;
	}

	@Column(name = "DBAMT", precision = 9)
	public BigDecimal getDbamt() {
		return this.dbamt;
	}

	public void setDbamt(BigDecimal dbamt) {
		this.dbamt = dbamt;
	}

	@Column(name = "CRAMT", precision = 9)
	public BigDecimal getCramt() {
		return this.cramt;
	}

	public void setCramt(BigDecimal cramt) {
		this.cramt = cramt;
	}

	@Column(name = "NAMEKEY", nullable = false, length = 1)
	public String getNamekey() {
		return this.namekey;
	}

	public void setNamekey(String namekey) {
		this.namekey = namekey;
	}

	@Column(name = "TOUR_K1", length = 1)
	public String getTourK1() {
		return this.tourK1;
	}

	public void setTourK1(String tourK1) {
		this.tourK1 = tourK1;
	}

	@Column(name = "DELKEY", length = 1)
	public String getDelkey() {
		return this.delkey;
	}

	public void setDelkey(String delkey) {
		this.delkey = delkey;
	}

	@Column(name = "OPUSER")
	public Integer getOpuser() {
		return this.opuser;
	}

	public void setOpuser(Integer opuser) {
		this.opuser = opuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OP_TIME", nullable = false, length = 19)
	public Date getOpTime() {
		return this.opTime;
	}

	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	@Column(name = "RECEIVE")
	public Integer getReceive() {
		return this.receive;
	}

	public void setReceive(Integer receive) {
		this.receive = receive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECEIVE_DT", length = 19)
	public Date getReceiveDt() {
		return this.receiveDt;
	}

	public void setReceiveDt(Date receiveDt) {
		this.receiveDt = receiveDt;
	}

	@Column(name = "SALESMAN")
	public Integer getSalesman() {
		return this.salesman;
	}

	public void setSalesman(Integer salesman) {
		this.salesman = salesman;
	}

	@Column(name = "PACT_NO", length = 16)
	public String getPactNo() {
		return this.pactNo;
	}

	public void setPactNo(String pactNo) {
		this.pactNo = pactNo;
	}

	@Column(name = "TOUR_KEY", length = 1)
	public Character getTourKey() {
		return this.tourKey;
	}

	public void setTourKey(Character tourKey) {
		this.tourKey = tourKey;
	}

	@Column(name = "REMARKS", length = 512)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "CFM_KEY", length = 1)
	public String getCfmKey() {
		return this.cfmKey;
	}

	public void setCfmKey(String cfmKey) {
		this.cfmKey = cfmKey;
	}

	@Column(name = "INV_KEY", length = 1)
	public String getInvKey() {
		return this.invKey;
	}

	public void setInvKey(String invKey) {
		this.invKey = invKey;
	}

	@Column(name = "INV_USER")
	public Integer getInvUser() {
		return this.invUser;
	}

	public void setInvUser(Integer invUser) {
		this.invUser = invUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DATE", length = 19)
	public Date getInvDate() {
		return this.invDate;
	}

	public void setInvDate(Date invDate) {
		this.invDate = invDate;
	}

	@Column(name = "READ_KEY", length = 1)
	public String getReadKey() {
		return this.readKey;
	}

	public void setReadKey(String readKey) {
		this.readKey = readKey;
	}

	@Column(name = "READ_USER")
	public Integer getReadUser() {
		return this.readUser;
	}

	public void setReadUser(Integer readUser) {
		this.readUser = readUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "READ_DATE", length = 19)
	public Date getReadDate() {
		return this.readDate;
	}

	public void setReadDate(Date readDate) {
		this.readDate = readDate;
	}

	@Column(name = "PLAN_KEY", length = 2)
	public String getPlanKey() {
		return this.planKey;
	}

	public void setPlanKey(String planKey) {
		this.planKey = planKey;
	}

	@Column(name = "FINAL_AMOUNT", precision = 11)
	public BigDecimal getFinalAmount() {
		return this.finalAmount;
	}

	public void setFinalAmount(BigDecimal finalAmount) {
		this.finalAmount = finalAmount;
	}

	@Column(name = "FINAL_USER")
	public Integer getFinalUser() {
		return this.finalUser;
	}

	public void setFinalUser(Integer finalUser) {
		this.finalUser = finalUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FINAL_DATE", length = 19)
	public Date getFinalDate() {
		return this.finalDate;
	}

	public void setFinalDate(Date finalDate) {
		this.finalDate = finalDate;
	}

	@Column(name = "FINAL_NOTE", length = 200)
	public String getFinalNote() {
		return this.finalNote;
	}

	public void setFinalNote(String finalNote) {
		this.finalNote = finalNote;
	}

	@Column(name = "WARRANT_FLAG", length = 1)
	public String getWarrantFlag() {
		return this.warrantFlag;
	}

	public void setWarrantFlag(String warrantFlag) {
		this.warrantFlag = warrantFlag;
	}

	@Column(name = "WARRANT_BY")
	public Integer getWarrantBy() {
		return this.warrantBy;
	}

	public void setWarrantBy(Integer warrantBy) {
		this.warrantBy = warrantBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WARRANT_DATE", length = 19)
	public Date getWarrantDate() {
		return this.warrantDate;
	}

	public void setWarrantDate(Date warrantDate) {
		this.warrantDate = warrantDate;
	}

	@Column(name = "WARRANT_MONEY", precision = 11)
	public BigDecimal getWarrantMoney() {
		return this.warrantMoney;
	}

	public void setWarrantMoney(BigDecimal warrantMoney) {
		this.warrantMoney = warrantMoney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_PAY_DATE", length = 19)
	public Date getLastPayDate() {
		return this.lastPayDate;
	}

	public void setLastPayDate(Date lastPayDate) {
		this.lastPayDate = lastPayDate;
	}

	@Column(name = "SOURCE", length = 2)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "WORKFLOW_ID")
	public String getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(String workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "CHECK_KEY", length = 1)
	public Character getCheckKey() {
		return this.checkKey;
	}

	public void setCheckKey(Character checkKey) {
		this.checkKey = checkKey;
	}

	@Column(name = "EXP_AMT", precision = 9)
	public BigDecimal getExpAmt() {
		return this.expAmt;
	}

	public void setExpAmt(BigDecimal expAmt) {
		this.expAmt = expAmt;
	}

	@Column(name = "ORDER_STATE", length = 1)
	public Character getOrderState() {
		return this.orderState;
	}

	public void setOrderState(Character orderState) {
		this.orderState = orderState;
	}

	@Column(name = "IS_AGREEON")
	public Integer getIsAgreeon() {
		return this.isAgreeon;
	}

	public void setIsAgreeon(Integer isAgreeon) {
		this.isAgreeon = isAgreeon;
	}

	@Column(name = "MEMBER_ID")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "LineNo", length = 10)
	public String getLineNo() {
		return this.lineNo;
	}

	public void setLineNo(String lineNo) {
		this.lineNo = lineNo;
	}

	@Column(name = "UserName", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "Mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ProductType", length = 1)
	public Character getProductType() {
		return this.productType;
	}

	public void setProductType(Character productType) {
		this.productType = productType;
	}

	@Column(name = "Adult")
	public Integer getAdult() {
		return this.adult;
	}

	public void setAdult(Integer adult) {
		this.adult = adult;
	}

	@Column(name = "Child")
	public Integer getChild() {
		return this.child;
	}

	public void setChild(Integer child) {
		this.child = child;
	}

	@Column(name = "RoomNum")
	public Integer getRoomNum() {
		return this.roomNum;
	}

	public void setRoomNum(Integer roomNum) {
		this.roomNum = roomNum;
	}

	@Column(name = "ProductState")
	public Integer getProductState() {
		return this.productState;
	}

	public void setProductState(Integer productState) {
		this.productState = productState;
	}

	@Column(name = "State")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OutDate", length = 19)
	public Date getOutDate() {
		return this.outDate;
	}

	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	@Column(name = "UserType")
	public Byte getUserType() {
		return this.userType;
	}

	public void setUserType(Byte userType) {
		this.userType = userType;
	}

	@Column(name = "BookingSource")
	public Byte getBookingSource() {
		return this.bookingSource;
	}

	public void setBookingSource(Byte bookingSource) {
		this.bookingSource = bookingSource;
	}

	@Column(name = "IsDelete")
	public Byte getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "CreatedBy")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CreatedByIp", length = 45)
	public String getCreatedByIp() {
		return this.createdByIp;
	}

	public void setCreatedByIp(String createdByIp) {
		this.createdByIp = createdByIp;
	}

	@Column(name = "ModifiedByIp", length = 45)
	public String getModifiedByIp() {
		return this.modifiedByIp;
	}

	public void setModifiedByIp(String modifiedByIp) {
		this.modifiedByIp = modifiedByIp;
	}

	@Column(name = "IsNeedInvoice")
	public Byte getIsNeedInvoice() {
		return this.isNeedInvoice;
	}

	public void setIsNeedInvoice(Byte isNeedInvoice) {
		this.isNeedInvoice = isNeedInvoice;
	}

	@Column(name = "InvoiceHead", length = 100)
	public String getInvoiceHead() {
		return this.invoiceHead;
	}

	public void setInvoiceHead(String invoiceHead) {
		this.invoiceHead = invoiceHead;
	}

	@Column(name = "InvoinceContent", length = 100)
	public String getInvoinceContent() {
		return this.invoinceContent;
	}

	public void setInvoinceContent(String invoinceContent) {
		this.invoinceContent = invoinceContent;
	}

	@Column(name = "PostWay")
	public Byte getPostWay() {
		return this.postWay;
	}

	public void setPostWay(Byte postWay) {
		this.postWay = postWay;
	}

}
