package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "tbl_customer", catalog = "tourismwork_db")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String code;
	private String name;
	private String shortName;
	private Integer teamId;
	private String countryCd;
	private String provinceCd;
	private String cityCd;
	private String district;
	private String registeredAdd;
	private String address;
	private String zip;
	private String phone;
	private String fax;
	private String contact;
	private String email;
	private Character type;
	private String passwd;
	private Character feature;
	private Character route;
	private Character resource;
	private Character structure;
	private Character payment;
	private String bussId;
	private Date bussDate;
	private BigDecimal creditAmt1;
	private BigDecimal creditAmt2;
	private Integer creditTime;
	private Character receiveMail;
	private String bankname;
	private String bankid;
	private String bcltname;
	private String status;
	private BigDecimal stay;
	private Character isActive;
	private boolean isSupplier;
	private boolean isAgent;
	private Character del;
	private Integer salesId;
	private Date created;
	private Integer createdby;
	private Date checked;
	private Integer checkedby;
	private Date updated;
	private Integer updatedby;

	public Customer() {
	}

	public Customer(String name, boolean isSupplier, boolean isAgent,
			Date updated) {
		this.name = name;
		this.isSupplier = isSupplier;
		this.isAgent = isAgent;
		this.updated = updated;
	}

	public Customer(String code, String name, String shortName, Integer teamId,
			String countryCd, String provinceCd, String cityCd,
			String district, String registeredAdd, String address, String zip,
			String phone, String fax, String contact, String email,
			Character type, String passwd, Character feature, Character route,
			Character resource, Character structure, Character payment,
			String bussId, Date bussDate, BigDecimal creditAmt1,
			BigDecimal creditAmt2, Integer creditTime, Character receiveMail,
			String bankname, String bankid, String bcltname, String status,
			BigDecimal stay, Character isActive, boolean isSupplier,
			boolean isAgent, Character del, Integer salesId, Date created,
			Integer createdby, Date checked, Integer checkedby, Date updated,
			Integer updatedby) {
		this.code = code;
		this.name = name;
		this.shortName = shortName;
		this.teamId = teamId;
		this.countryCd = countryCd;
		this.provinceCd = provinceCd;
		this.cityCd = cityCd;
		this.district = district;
		this.registeredAdd = registeredAdd;
		this.address = address;
		this.zip = zip;
		this.phone = phone;
		this.fax = fax;
		this.contact = contact;
		this.email = email;
		this.type = type;
		this.passwd = passwd;
		this.feature = feature;
		this.route = route;
		this.resource = resource;
		this.structure = structure;
		this.payment = payment;
		this.bussId = bussId;
		this.bussDate = bussDate;
		this.creditAmt1 = creditAmt1;
		this.creditAmt2 = creditAmt2;
		this.creditTime = creditTime;
		this.receiveMail = receiveMail;
		this.bankname = bankname;
		this.bankid = bankid;
		this.bcltname = bcltname;
		this.status = status;
		this.stay = stay;
		this.isActive = isActive;
		this.isSupplier = isSupplier;
		this.isAgent = isAgent;
		this.del = del;
		this.salesId = salesId;
		this.created = created;
		this.createdby = createdby;
		this.checked = checked;
		this.checkedby = checkedby;
		this.updated = updated;
		this.updatedby = updatedby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SHORT_NAME", length = 20)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "TEAM_ID")
	public Integer getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	@Column(name = "COUNTRY_CD", length = 6)
	public String getCountryCd() {
		return this.countryCd;
	}

	public void setCountryCd(String countryCd) {
		this.countryCd = countryCd;
	}

	@Column(name = "PROVINCE_CD", length = 6)
	public String getProvinceCd() {
		return this.provinceCd;
	}

	public void setProvinceCd(String provinceCd) {
		this.provinceCd = provinceCd;
	}

	@Column(name = "CITY_CD", length = 6)
	public String getCityCd() {
		return this.cityCd;
	}

	public void setCityCd(String cityCd) {
		this.cityCd = cityCd;
	}

	@Column(name = "DISTRICT", length = 40)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "REGISTERED_ADD", length = 80)
	public String getRegisteredAdd() {
		return this.registeredAdd;
	}

	public void setRegisteredAdd(String registeredAdd) {
		this.registeredAdd = registeredAdd;
	}

	@Column(name = "ADDRESS", length = 80)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "ZIP", length = 12)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "PHONE", length = 40)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "FAX", length = 40)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "CONTACT", length = 20)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "EMAIL", length = 120)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TYPE", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "PASSWD", length = 20)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "FEATURE", length = 1)
	public Character getFeature() {
		return this.feature;
	}

	public void setFeature(Character feature) {
		this.feature = feature;
	}

	@Column(name = "ROUTE", length = 1)
	public Character getRoute() {
		return this.route;
	}

	public void setRoute(Character route) {
		this.route = route;
	}

	@Column(name = "RESOURCE", length = 1)
	public Character getResource() {
		return this.resource;
	}

	public void setResource(Character resource) {
		this.resource = resource;
	}

	@Column(name = "STRUCTURE", length = 1)
	public Character getStructure() {
		return this.structure;
	}

	public void setStructure(Character structure) {
		this.structure = structure;
	}

	@Column(name = "PAYMENT", length = 1)
	public Character getPayment() {
		return this.payment;
	}

	public void setPayment(Character payment) {
		this.payment = payment;
	}

	@Column(name = "BUSS_ID", length = 30)
	public String getBussId() {
		return this.bussId;
	}

	public void setBussId(String bussId) {
		this.bussId = bussId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BUSS_DATE", length = 19)
	public Date getBussDate() {
		return this.bussDate;
	}

	public void setBussDate(Date bussDate) {
		this.bussDate = bussDate;
	}

	@Column(name = "CREDIT_AMT1", precision = 11)
	public BigDecimal getCreditAmt1() {
		return this.creditAmt1;
	}

	public void setCreditAmt1(BigDecimal creditAmt1) {
		this.creditAmt1 = creditAmt1;
	}

	@Column(name = "CREDIT_AMT2", precision = 11)
	public BigDecimal getCreditAmt2() {
		return this.creditAmt2;
	}

	public void setCreditAmt2(BigDecimal creditAmt2) {
		this.creditAmt2 = creditAmt2;
	}

	@Column(name = "CREDIT_TIME")
	public Integer getCreditTime() {
		return this.creditTime;
	}

	public void setCreditTime(Integer creditTime) {
		this.creditTime = creditTime;
	}

	@Column(name = "RECEIVE_MAIL", length = 1)
	public Character getReceiveMail() {
		return this.receiveMail;
	}

	public void setReceiveMail(Character receiveMail) {
		this.receiveMail = receiveMail;
	}

	@Column(name = "BANKNAME", length = 50)
	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	@Column(name = "BANKID", length = 50)
	public String getBankid() {
		return this.bankid;
	}

	public void setBankid(String bankid) {
		this.bankid = bankid;
	}

	@Column(name = "BCLTNAME", length = 50)
	public String getBcltname() {
		return this.bcltname;
	}

	public void setBcltname(String bcltname) {
		this.bcltname = bcltname;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "STAY", precision = 4, scale = 3)
	public BigDecimal getStay() {
		return this.stay;
	}

	public void setStay(BigDecimal stay) {
		this.stay = stay;
	}

	@Column(name = "IS_ACTIVE", length = 1)
	public Character getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Character isActive) {
		this.isActive = isActive;
	}

	@Column(name = "IS_SUPPLIER", nullable = false)
	public boolean isIsSupplier() {
		return this.isSupplier;
	}

	public void setIsSupplier(boolean isSupplier) {
		this.isSupplier = isSupplier;
	}

	@Column(name = "IS_AGENT", nullable = false)
	public boolean isIsAgent() {
		return this.isAgent;
	}

	public void setIsAgent(boolean isAgent) {
		this.isAgent = isAgent;
	}

	@Column(name = "DEL", length = 1)
	public Character getDel() {
		return this.del;
	}

	public void setDel(Character del) {
		this.del = del;
	}

	@Column(name = "SALES_ID")
	public Integer getSalesId() {
		return this.salesId;
	}

	public void setSalesId(Integer salesId) {
		this.salesId = salesId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "CREATEDBY")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHECKED", length = 19)
	public Date getChecked() {
		return this.checked;
	}

	public void setChecked(Date checked) {
		this.checked = checked;
	}

	@Column(name = "CHECKEDBY")
	public Integer getCheckedby() {
		return this.checkedby;
	}

	public void setCheckedby(Integer checkedby) {
		this.checkedby = checkedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED", nullable = false, length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "UPDATEDBY")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

}
