package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Destination generated by hbm2java
 */
@Entity
@Table(name = "tbl_destination", catalog = "tourismwork_db")
public class Destination implements java.io.Serializable {

	private Integer destId;
	private Destination destination;
	private String code;
	private String cnName;
	private String fullName;
	private Character level;
	private Character nextKey;
	private String keywords;
	private String destDesc;
	private String metaKeywords;
	private String metaDesc;
	private Character classType;
	private Set<Destination> destinations = new HashSet<Destination>(0);

	public Destination() {
	}

	public Destination(String code) {
		this.code = code;
	}

	public Destination(Destination destination, String code, String cnName,
			String fullName, Character level, Character nextKey,
			String keywords, String destDesc, String metaKeywords,
			String metaDesc, Character classType, Set<Destination> destinations) {
		this.destination = destination;
		this.code = code;
		this.cnName = cnName;
		this.fullName = fullName;
		this.level = level;
		this.nextKey = nextKey;
		this.keywords = keywords;
		this.destDesc = destDesc;
		this.metaKeywords = metaKeywords;
		this.metaDesc = metaDesc;
		this.classType = classType;
		this.destinations = destinations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DEST_ID", unique = true, nullable = false)
	public Integer getDestId() {
		return this.destId;
	}

	public void setDestId(Integer destId) {
		this.destId = destId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID")
	public Destination getDestination() {
		return this.destination;
	}

	public void setDestination(Destination destination) {
		this.destination = destination;
	}

	@Column(name = "CODE", nullable = false, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CN_NAME", length = 30)
	public String getCnName() {
		return this.cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	@Column(name = "FULL_NAME", length = 120)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "LEVEL", length = 1)
	public Character getLevel() {
		return this.level;
	}

	public void setLevel(Character level) {
		this.level = level;
	}

	@Column(name = "NEXT_KEY", length = 1)
	public Character getNextKey() {
		return this.nextKey;
	}

	public void setNextKey(Character nextKey) {
		this.nextKey = nextKey;
	}

	@Column(name = "KEYWORDS", length = 50)
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Column(name = "DEST_DESC", length = 50)
	public String getDestDesc() {
		return this.destDesc;
	}

	public void setDestDesc(String destDesc) {
		this.destDesc = destDesc;
	}

	@Column(name = "META_KEYWORDS", length = 50)
	public String getMetaKeywords() {
		return this.metaKeywords;
	}

	public void setMetaKeywords(String metaKeywords) {
		this.metaKeywords = metaKeywords;
	}

	@Column(name = "META_DESC", length = 50)
	public String getMetaDesc() {
		return this.metaDesc;
	}

	public void setMetaDesc(String metaDesc) {
		this.metaDesc = metaDesc;
	}

	@Column(name = "CLASS_TYPE", length = 1)
	public Character getClassType() {
		return this.classType;
	}

	public void setClassType(Character classType) {
		this.classType = classType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destination")
	public Set<Destination> getDestinations() {
		return this.destinations;
	}

	public void setDestinations(Set<Destination> destinations) {
		this.destinations = destinations;
	}

}
