package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "tbl_district", catalog = "tourismwork_db")
public class District implements java.io.Serializable {

	private String districtNo;
	private Country country;
	private String cnName;
	private String cnNote;
	private String mapAddress1;
	private String mapAddress2;
	private String duchy;
	private Set<Sight> sights = new HashSet<Sight>(0);

	public District() {
	}

	public District(String districtNo, Country country, String cnName) {
		this.districtNo = districtNo;
		this.country = country;
		this.cnName = cnName;
	}

	public District(String districtNo, Country country, String cnName,
			String cnNote, String mapAddress1, String mapAddress2,
			String duchy, Set<Sight> sights) {
		this.districtNo = districtNo;
		this.country = country;
		this.cnName = cnName;
		this.cnNote = cnNote;
		this.mapAddress1 = mapAddress1;
		this.mapAddress2 = mapAddress2;
		this.duchy = duchy;
		this.sights = sights;
	}

	@Id
	@Column(name = "DISTRICT_NO", unique = true, nullable = false, length = 10)
	public String getDistrictNo() {
		return this.districtNo;
	}

	public void setDistrictNo(String districtNo) {
		this.districtNo = districtNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "CN_NAME", nullable = false, length = 30)
	public String getCnName() {
		return this.cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	@Column(name = "CN_NOTE", length = 2000)
	public String getCnNote() {
		return this.cnNote;
	}

	public void setCnNote(String cnNote) {
		this.cnNote = cnNote;
	}

	@Column(name = "MAP_ADDRESS1", length = 50)
	public String getMapAddress1() {
		return this.mapAddress1;
	}

	public void setMapAddress1(String mapAddress1) {
		this.mapAddress1 = mapAddress1;
	}

	@Column(name = "MAP_ADDRESS2", length = 50)
	public String getMapAddress2() {
		return this.mapAddress2;
	}

	public void setMapAddress2(String mapAddress2) {
		this.mapAddress2 = mapAddress2;
	}

	@Column(name = "DUCHY", length = 2)
	public String getDuchy() {
		return this.duchy;
	}

	public void setDuchy(String duchy) {
		this.duchy = duchy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Sight> getSights() {
		return this.sights;
	}

	public void setSights(Set<Sight> sights) {
		this.sights = sights;
	}

}
