package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineDescription generated by hbm2java
 */
@Entity
@Table(name = "tbl_line_desc", catalog = "tourismwork_db")
public class LineDescription implements java.io.Serializable {

	private Integer id;
	private String lineNo;
	private String type;
	private String item;
	private String description;
	private Integer sortOrder;

	public LineDescription() {
	}

	public LineDescription(String lineNo, String type) {
		this.lineNo = lineNo;
		this.type = type;
	}

	public LineDescription(String lineNo, String type, String item,
			String description, Integer sortOrder) {
		this.lineNo = lineNo;
		this.type = type;
		this.item = item;
		this.description = description;
		this.sortOrder = sortOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "LINE_NO", nullable = false, length = 8)
	public String getLineNo() {
		return this.lineNo;
	}

	public void setLineNo(String lineNo) {
		this.lineNo = lineNo;
	}

	@Column(name = "TYPE", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "ITEM", length = 100)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "DESCRIPTION", length = 1500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SORT_ORDER")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
