package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LineDistrict generated by hbm2java
 */
@Entity
@Table(name = "tbl_line_district", catalog = "tourismwork_db")
public class LineDistrict implements java.io.Serializable {

	private LineDistrictId id;

	public LineDistrict() {
	}

	public LineDistrict(LineDistrictId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lineNo", column = @Column(name = "LINE_NO", nullable = false, length = 8)),
			@AttributeOverride(name = "districtNo", column = @Column(name = "DISTRICT_NO", nullable = false, length = 10)) })
	public LineDistrictId getId() {
		return this.id;
	}

	public void setId(LineDistrictId id) {
		this.id = id;
	}

}
