package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Line generated by hbm2java
 */
@Entity
@Table(name = "tbl_line", catalog = "tourismwork_db")
public class Line implements java.io.Serializable {

	private String lineNo;
	private Team team;
	private City city;
	private String lineName;
	private Integer day;
	private Integer assignedUserId;
	private Integer opTeamId;
	private Character classKey1;
	private Character classKey2;
	private Character classKey3;
	private String classKey4;
	private Integer classKey5;
	private String classKey6;
	private Character classKey7;
	private String firstCity;
	private String title;
	private String description;
	private boolean isActive;
	private Character delKey;
	private Character newKey;
	private Integer crUser;
	private Date crDate;
	private Integer opUser;
	private Date opDate;
	private String fitType;
	private Integer OPax;
	private Integer ONight1;
	private Integer ONight2;
	private String comOwnExpense;
	private String perOwnExpense;
	private Integer traitType;
	private String portOfEntry;
	private String portOfDeparture;
	private String percentage;
	private String profit;
	private String flag;
	private String guestPercentage;
	private String guestProfit;
	private Byte isHot;
	private Byte canDefer;
	private Integer minDays;
	private Integer minNights;
	private String airwaysId;
	private Integer createdBy;
	private Date createdDate;
	private String createdByIp;
	private Integer modifiedBy;
	private Date modifiedDate;
	private String modifiedByIp;
	private Set<Plan> plans = new HashSet<Plan>(0);

	public Line() {
	}

	public Line(String lineNo, Team team, String lineName, boolean isActive,
			String flag) {
		this.lineNo = lineNo;
		this.team = team;
		this.lineName = lineName;
		this.isActive = isActive;
		this.flag = flag;
	}

	public Line(String lineNo, Team team, City city, String lineName,
			Integer day, Integer assignedUserId, Integer opTeamId,
			Character classKey1, Character classKey2, Character classKey3,
			String classKey4, Integer classKey5, String classKey6,
			Character classKey7, String firstCity, String title,
			String description, boolean isActive, Character delKey,
			Character newKey, Integer crUser, Date crDate, Integer opUser,
			Date opDate, String fitType, Integer OPax, Integer ONight1,
			Integer ONight2, String comOwnExpense, String perOwnExpense,
			Integer traitType, String portOfEntry, String portOfDeparture,
			String percentage, String profit, String flag,
			String guestPercentage, String guestProfit, Byte isHot,
			Byte canDefer, Integer minDays, Integer minNights,
			String airwaysId, Integer createdBy, Date createdDate,
			String createdByIp, Integer modifiedBy, Date modifiedDate,
			String modifiedByIp, Set<Plan> plans) {
		this.lineNo = lineNo;
		this.team = team;
		this.city = city;
		this.lineName = lineName;
		this.day = day;
		this.assignedUserId = assignedUserId;
		this.opTeamId = opTeamId;
		this.classKey1 = classKey1;
		this.classKey2 = classKey2;
		this.classKey3 = classKey3;
		this.classKey4 = classKey4;
		this.classKey5 = classKey5;
		this.classKey6 = classKey6;
		this.classKey7 = classKey7;
		this.firstCity = firstCity;
		this.title = title;
		this.description = description;
		this.isActive = isActive;
		this.delKey = delKey;
		this.newKey = newKey;
		this.crUser = crUser;
		this.crDate = crDate;
		this.opUser = opUser;
		this.opDate = opDate;
		this.fitType = fitType;
		this.OPax = OPax;
		this.ONight1 = ONight1;
		this.ONight2 = ONight2;
		this.comOwnExpense = comOwnExpense;
		this.perOwnExpense = perOwnExpense;
		this.traitType = traitType;
		this.portOfEntry = portOfEntry;
		this.portOfDeparture = portOfDeparture;
		this.percentage = percentage;
		this.profit = profit;
		this.flag = flag;
		this.guestPercentage = guestPercentage;
		this.guestProfit = guestProfit;
		this.isHot = isHot;
		this.canDefer = canDefer;
		this.minDays = minDays;
		this.minNights = minNights;
		this.airwaysId = airwaysId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.createdByIp = createdByIp;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.modifiedByIp = modifiedByIp;
		this.plans = plans;
	}

	@Id
	@Column(name = "LINE_NO", unique = true, nullable = false, length = 8)
	public String getLineNo() {
		return this.lineNo;
	}

	public void setLineNo(String lineNo) {
		this.lineNo = lineNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEAM_ID", nullable = false)
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUT_CITY")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "LINE_NAME", nullable = false, length = 60)
	public String getLineName() {
		return this.lineName;
	}

	public void setLineName(String lineName) {
		this.lineName = lineName;
	}

	@Column(name = "DAY")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "ASSIGNED_USER_ID")
	public Integer getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(Integer assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	@Column(name = "OP_TEAM_ID")
	public Integer getOpTeamId() {
		return this.opTeamId;
	}

	public void setOpTeamId(Integer opTeamId) {
		this.opTeamId = opTeamId;
	}

	@Column(name = "CLASS_KEY1", length = 1)
	public Character getClassKey1() {
		return this.classKey1;
	}

	public void setClassKey1(Character classKey1) {
		this.classKey1 = classKey1;
	}

	@Column(name = "CLASS_KEY2", length = 1)
	public Character getClassKey2() {
		return this.classKey2;
	}

	public void setClassKey2(Character classKey2) {
		this.classKey2 = classKey2;
	}

	@Column(name = "CLASS_KEY3", length = 1)
	public Character getClassKey3() {
		return this.classKey3;
	}

	public void setClassKey3(Character classKey3) {
		this.classKey3 = classKey3;
	}

	@Column(name = "CLASS_KEY4", length = 2)
	public String getClassKey4() {
		return this.classKey4;
	}

	public void setClassKey4(String classKey4) {
		this.classKey4 = classKey4;
	}

	@Column(name = "CLASS_KEY5")
	public Integer getClassKey5() {
		return this.classKey5;
	}

	public void setClassKey5(Integer classKey5) {
		this.classKey5 = classKey5;
	}

	@Column(name = "CLASS_KEY6", length = 2)
	public String getClassKey6() {
		return this.classKey6;
	}

	public void setClassKey6(String classKey6) {
		this.classKey6 = classKey6;
	}

	@Column(name = "CLASS_KEY7", length = 1)
	public Character getClassKey7() {
		return this.classKey7;
	}

	public void setClassKey7(Character classKey7) {
		this.classKey7 = classKey7;
	}

	@Column(name = "FIRST_CITY", length = 4)
	public String getFirstCity() {
		return this.firstCity;
	}

	public void setFirstCity(String firstCity) {
		this.firstCity = firstCity;
	}

	@Column(name = "TITLE", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IS_ACTIVE", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "DEL_KEY", length = 1)
	public Character getDelKey() {
		return this.delKey;
	}

	public void setDelKey(Character delKey) {
		this.delKey = delKey;
	}

	@Column(name = "NEW_KEY", length = 1)
	public Character getNewKey() {
		return this.newKey;
	}

	public void setNewKey(Character newKey) {
		this.newKey = newKey;
	}

	@Column(name = "CR_USER")
	public Integer getCrUser() {
		return this.crUser;
	}

	public void setCrUser(Integer crUser) {
		this.crUser = crUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DATE", length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Column(name = "OP_USER")
	public Integer getOpUser() {
		return this.opUser;
	}

	public void setOpUser(Integer opUser) {
		this.opUser = opUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OP_DATE", length = 19)
	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	@Column(name = "FIT_TYPE", length = 2)
	public String getFitType() {
		return this.fitType;
	}

	public void setFitType(String fitType) {
		this.fitType = fitType;
	}

	@Column(name = "O_PAX")
	public Integer getOPax() {
		return this.OPax;
	}

	public void setOPax(Integer OPax) {
		this.OPax = OPax;
	}

	@Column(name = "O_NIGHT1")
	public Integer getONight1() {
		return this.ONight1;
	}

	public void setONight1(Integer ONight1) {
		this.ONight1 = ONight1;
	}

	@Column(name = "O_NIGHT2")
	public Integer getONight2() {
		return this.ONight2;
	}

	public void setONight2(Integer ONight2) {
		this.ONight2 = ONight2;
	}

	@Column(name = "COM_OWN_EXPENSE", length = 500)
	public String getComOwnExpense() {
		return this.comOwnExpense;
	}

	public void setComOwnExpense(String comOwnExpense) {
		this.comOwnExpense = comOwnExpense;
	}

	@Column(name = "PER_OWN_EXPENSE", length = 500)
	public String getPerOwnExpense() {
		return this.perOwnExpense;
	}

	public void setPerOwnExpense(String perOwnExpense) {
		this.perOwnExpense = perOwnExpense;
	}

	@Column(name = "TRAIT_TYPE")
	public Integer getTraitType() {
		return this.traitType;
	}

	public void setTraitType(Integer traitType) {
		this.traitType = traitType;
	}

	@Column(name = "PORT_OF_ENTRY", length = 20)
	public String getPortOfEntry() {
		return this.portOfEntry;
	}

	public void setPortOfEntry(String portOfEntry) {
		this.portOfEntry = portOfEntry;
	}

	@Column(name = "PORT_OF_DEPARTURE", length = 20)
	public String getPortOfDeparture() {
		return this.portOfDeparture;
	}

	public void setPortOfDeparture(String portOfDeparture) {
		this.portOfDeparture = portOfDeparture;
	}

	@Column(name = "PERCENTAGE", length = 10)
	public String getPercentage() {
		return this.percentage;
	}

	public void setPercentage(String percentage) {
		this.percentage = percentage;
	}

	@Column(name = "PROFIT", length = 10)
	public String getProfit() {
		return this.profit;
	}

	public void setProfit(String profit) {
		this.profit = profit;
	}

	@Column(name = "FLAG", nullable = false, length = 1)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "GUEST_PERCENTAGE", length = 10)
	public String getGuestPercentage() {
		return this.guestPercentage;
	}

	public void setGuestPercentage(String guestPercentage) {
		this.guestPercentage = guestPercentage;
	}

	@Column(name = "GUEST_PROFIT", length = 10)
	public String getGuestProfit() {
		return this.guestProfit;
	}

	public void setGuestProfit(String guestProfit) {
		this.guestProfit = guestProfit;
	}

	@Column(name = "IS_HOT")
	public Byte getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Byte isHot) {
		this.isHot = isHot;
	}

	@Column(name = "CAN_DEFER")
	public Byte getCanDefer() {
		return this.canDefer;
	}

	public void setCanDefer(Byte canDefer) {
		this.canDefer = canDefer;
	}

	@Column(name = "MIN_DAYS")
	public Integer getMinDays() {
		return this.minDays;
	}

	public void setMinDays(Integer minDays) {
		this.minDays = minDays;
	}

	@Column(name = "MIN_NIGHTS")
	public Integer getMinNights() {
		return this.minNights;
	}

	public void setMinNights(Integer minNights) {
		this.minNights = minNights;
	}

	@Column(name = "AIRWAYS_ID", length = 20)
	public String getAirwaysId() {
		return this.airwaysId;
	}

	public void setAirwaysId(String airwaysId) {
		this.airwaysId = airwaysId;
	}

	@Column(name = "CreatedBy")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CreatedByIP", length = 20)
	public String getCreatedByIp() {
		return this.createdByIp;
	}

	public void setCreatedByIp(String createdByIp) {
		this.createdByIp = createdByIp;
	}

	@Column(name = "ModifiedBy")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedDate", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "ModifiedByIP", length = 20)
	public String getModifiedByIp() {
		return this.modifiedByIp;
	}

	public void setModifiedByIp(String modifiedByIp) {
		this.modifiedByIp = modifiedByIp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "line")
	public Set<Plan> getPlans() {
		return this.plans;
	}

	public void setPlans(Set<Plan> plans) {
		this.plans = plans;
	}

}
