package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LinePrice generated by hbm2java
 */
@Entity
@Table(name = "tbl_line_price", catalog = "tourismwork_db")
public class LinePrice implements java.io.Serializable {

	private String recNo;
	private String lineNo;
	private Character priceKey;
	private String subject;
	private BigDecimal price1;
	private BigDecimal price2;
	private BigDecimal price3;
	private BigDecimal price4;
	private Date SDate;
	private Date EDate;
	private String weekBit;
	private BigDecimal subscription;
	private BigDecimal difference;
	private Integer crUser;
	private Date crDate;
	private Integer opUser;
	private Date opDate;
	private BigDecimal cost1;
	private BigDecimal cost2;
	private BigDecimal cost3;
	private BigDecimal cost4;
	private BigDecimal cost5;
	private BigDecimal cost6;
	private BigDecimal cost7;
	private BigDecimal cost8;
	private BigDecimal cost9;
	private BigDecimal cost10;
	private BigDecimal cost11;
	private BigDecimal cost12;
	private String reamrks;
	private String currency;
	private BigDecimal roe;
	private BigDecimal unitPrice;
	private BigDecimal backMoney;
	private BigDecimal afieldDuty;

	public LinePrice() {
	}

	public LinePrice(String recNo, Date opDate) {
		this.recNo = recNo;
		this.opDate = opDate;
	}

	public LinePrice(String recNo, String lineNo, Character priceKey,
			String subject, BigDecimal price1, BigDecimal price2,
			BigDecimal price3, BigDecimal price4, Date SDate, Date EDate,
			String weekBit, BigDecimal subscription, BigDecimal difference,
			Integer crUser, Date crDate, Integer opUser, Date opDate,
			BigDecimal cost1, BigDecimal cost2, BigDecimal cost3,
			BigDecimal cost4, BigDecimal cost5, BigDecimal cost6,
			BigDecimal cost7, BigDecimal cost8, BigDecimal cost9,
			BigDecimal cost10, BigDecimal cost11, BigDecimal cost12,
			String reamrks, String currency, BigDecimal roe,
			BigDecimal unitPrice, BigDecimal backMoney, BigDecimal afieldDuty) {
		this.recNo = recNo;
		this.lineNo = lineNo;
		this.priceKey = priceKey;
		this.subject = subject;
		this.price1 = price1;
		this.price2 = price2;
		this.price3 = price3;
		this.price4 = price4;
		this.SDate = SDate;
		this.EDate = EDate;
		this.weekBit = weekBit;
		this.subscription = subscription;
		this.difference = difference;
		this.crUser = crUser;
		this.crDate = crDate;
		this.opUser = opUser;
		this.opDate = opDate;
		this.cost1 = cost1;
		this.cost2 = cost2;
		this.cost3 = cost3;
		this.cost4 = cost4;
		this.cost5 = cost5;
		this.cost6 = cost6;
		this.cost7 = cost7;
		this.cost8 = cost8;
		this.cost9 = cost9;
		this.cost10 = cost10;
		this.cost11 = cost11;
		this.cost12 = cost12;
		this.reamrks = reamrks;
		this.currency = currency;
		this.roe = roe;
		this.unitPrice = unitPrice;
		this.backMoney = backMoney;
		this.afieldDuty = afieldDuty;
	}

	@Id
	@Column(name = "REC_NO", unique = true, nullable = false, length = 8)
	public String getRecNo() {
		return this.recNo;
	}

	public void setRecNo(String recNo) {
		this.recNo = recNo;
	}

	@Column(name = "LINE_NO", length = 8)
	public String getLineNo() {
		return this.lineNo;
	}

	public void setLineNo(String lineNo) {
		this.lineNo = lineNo;
	}

	@Column(name = "PRICE_KEY", length = 1)
	public Character getPriceKey() {
		return this.priceKey;
	}

	public void setPriceKey(Character priceKey) {
		this.priceKey = priceKey;
	}

	@Column(name = "SUBJECT", length = 80)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "PRICE1", precision = 9)
	public BigDecimal getPrice1() {
		return this.price1;
	}

	public void setPrice1(BigDecimal price1) {
		this.price1 = price1;
	}

	@Column(name = "PRICE2", precision = 9)
	public BigDecimal getPrice2() {
		return this.price2;
	}

	public void setPrice2(BigDecimal price2) {
		this.price2 = price2;
	}

	@Column(name = "PRICE3", precision = 9)
	public BigDecimal getPrice3() {
		return this.price3;
	}

	public void setPrice3(BigDecimal price3) {
		this.price3 = price3;
	}

	@Column(name = "PRICE4", precision = 9)
	public BigDecimal getPrice4() {
		return this.price4;
	}

	public void setPrice4(BigDecimal price4) {
		this.price4 = price4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "S_DATE", length = 19)
	public Date getSDate() {
		return this.SDate;
	}

	public void setSDate(Date SDate) {
		this.SDate = SDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E_DATE", length = 19)
	public Date getEDate() {
		return this.EDate;
	}

	public void setEDate(Date EDate) {
		this.EDate = EDate;
	}

	@Column(name = "WEEK_BIT", length = 7)
	public String getWeekBit() {
		return this.weekBit;
	}

	public void setWeekBit(String weekBit) {
		this.weekBit = weekBit;
	}

	@Column(name = "SUBSCRIPTION", precision = 9)
	public BigDecimal getSubscription() {
		return this.subscription;
	}

	public void setSubscription(BigDecimal subscription) {
		this.subscription = subscription;
	}

	@Column(name = "DIFFERENCE", precision = 9)
	public BigDecimal getDifference() {
		return this.difference;
	}

	public void setDifference(BigDecimal difference) {
		this.difference = difference;
	}

	@Column(name = "CR_USER")
	public Integer getCrUser() {
		return this.crUser;
	}

	public void setCrUser(Integer crUser) {
		this.crUser = crUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DATE", length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Column(name = "OP_USER")
	public Integer getOpUser() {
		return this.opUser;
	}

	public void setOpUser(Integer opUser) {
		this.opUser = opUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OP_DATE", nullable = false, length = 19)
	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

	@Column(name = "COST1", precision = 11)
	public BigDecimal getCost1() {
		return this.cost1;
	}

	public void setCost1(BigDecimal cost1) {
		this.cost1 = cost1;
	}

	@Column(name = "COST2", precision = 11)
	public BigDecimal getCost2() {
		return this.cost2;
	}

	public void setCost2(BigDecimal cost2) {
		this.cost2 = cost2;
	}

	@Column(name = "COST3", precision = 11)
	public BigDecimal getCost3() {
		return this.cost3;
	}

	public void setCost3(BigDecimal cost3) {
		this.cost3 = cost3;
	}

	@Column(name = "COST4", precision = 11)
	public BigDecimal getCost4() {
		return this.cost4;
	}

	public void setCost4(BigDecimal cost4) {
		this.cost4 = cost4;
	}

	@Column(name = "COST5", precision = 11)
	public BigDecimal getCost5() {
		return this.cost5;
	}

	public void setCost5(BigDecimal cost5) {
		this.cost5 = cost5;
	}

	@Column(name = "COST6", precision = 11)
	public BigDecimal getCost6() {
		return this.cost6;
	}

	public void setCost6(BigDecimal cost6) {
		this.cost6 = cost6;
	}

	@Column(name = "COST7", precision = 11)
	public BigDecimal getCost7() {
		return this.cost7;
	}

	public void setCost7(BigDecimal cost7) {
		this.cost7 = cost7;
	}

	@Column(name = "COST8", precision = 11)
	public BigDecimal getCost8() {
		return this.cost8;
	}

	public void setCost8(BigDecimal cost8) {
		this.cost8 = cost8;
	}

	@Column(name = "COST9", precision = 11)
	public BigDecimal getCost9() {
		return this.cost9;
	}

	public void setCost9(BigDecimal cost9) {
		this.cost9 = cost9;
	}

	@Column(name = "COST10", precision = 11)
	public BigDecimal getCost10() {
		return this.cost10;
	}

	public void setCost10(BigDecimal cost10) {
		this.cost10 = cost10;
	}

	@Column(name = "COST11", precision = 11)
	public BigDecimal getCost11() {
		return this.cost11;
	}

	public void setCost11(BigDecimal cost11) {
		this.cost11 = cost11;
	}

	@Column(name = "COST12", precision = 11)
	public BigDecimal getCost12() {
		return this.cost12;
	}

	public void setCost12(BigDecimal cost12) {
		this.cost12 = cost12;
	}

	@Column(name = "REAMRKS", length = 100)
	public String getReamrks() {
		return this.reamrks;
	}

	public void setReamrks(String reamrks) {
		this.reamrks = reamrks;
	}

	@Column(name = "CURRENCY", length = 10)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "ROE", precision = 7)
	public BigDecimal getRoe() {
		return this.roe;
	}

	public void setRoe(BigDecimal roe) {
		this.roe = roe;
	}

	@Column(name = "UNIT_PRICE", precision = 11)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "BACK_MONEY", precision = 11)
	public BigDecimal getBackMoney() {
		return this.backMoney;
	}

	public void setBackMoney(BigDecimal backMoney) {
		this.backMoney = backMoney;
	}

	@Column(name = "AFIELD_DUTY", precision = 11)
	public BigDecimal getAfieldDuty() {
		return this.afieldDuty;
	}

	public void setAfieldDuty(BigDecimal afieldDuty) {
		this.afieldDuty = afieldDuty;
	}

}
