package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LineVisa generated by hbm2java
 */
@Entity
@Table(name = "tbl_line_visa", catalog = "tourismwork_db")
public class LineVisa implements java.io.Serializable {

	private LineVisaId id;

	public LineVisa() {
	}

	public LineVisa(LineVisaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lineNo", column = @Column(name = "LINE_NO", nullable = false, length = 8)),
			@AttributeOverride(name = "recNo", column = @Column(name = "REC_NO", nullable = false, length = 10)) })
	public LineVisaId getId() {
		return this.id;
	}

	public void setId(LineVisaId id) {
		this.id = id;
	}

}
