package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Lists generated by hbm2java
 */
@Entity
@Table(name = "tbl_lists", catalog = "tourismwork_db", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ListName", "Value" }))
public class Lists implements java.io.Serializable {

	private Integer entryId;
	private String listName;
	private String value;
	private String text;
	private int parentId;
	private int level;
	private byte enabled;
	private int sortOrder;
	private int definitionId;
	private String description;
	private byte systemList;

	public Lists() {
	}

	public Lists(String listName, String value, String text, int parentId,
			int level, byte enabled, int sortOrder, int definitionId,
			byte systemList) {
		this.listName = listName;
		this.value = value;
		this.text = text;
		this.parentId = parentId;
		this.level = level;
		this.enabled = enabled;
		this.sortOrder = sortOrder;
		this.definitionId = definitionId;
		this.systemList = systemList;
	}

	public Lists(String listName, String value, String text, int parentId,
			int level, byte enabled, int sortOrder, int definitionId,
			String description, byte systemList) {
		this.listName = listName;
		this.value = value;
		this.text = text;
		this.parentId = parentId;
		this.level = level;
		this.enabled = enabled;
		this.sortOrder = sortOrder;
		this.definitionId = definitionId;
		this.description = description;
		this.systemList = systemList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EntryID", unique = true, nullable = false)
	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	@Column(name = "ListName", nullable = false, length = 50)
	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	@Column(name = "Value", nullable = false, length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "Text", nullable = false, length = 150)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "ParentID", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "Level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "Enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	@Column(name = "SortOrder", nullable = false)
	public int getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(int sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "DefinitionID", nullable = false)
	public int getDefinitionId() {
		return this.definitionId;
	}

	public void setDefinitionId(int definitionId) {
		this.definitionId = definitionId;
	}

	@Column(name = "Description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SystemList", nullable = false)
	public byte getSystemList() {
		return this.systemList;
	}

	public void setSystemList(byte systemList) {
		this.systemList = systemList;
	}

}
