package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlanPrice generated by hbm2java
 */
@Entity
@Table(name = "tbl_plan_price", catalog = "tourismwork_db")
public class PlanPrice implements java.io.Serializable {

	private Integer id;
	private String planNo;
	private String priceNo;

	public PlanPrice() {
	}

	public PlanPrice(String planNo, String priceNo) {
		this.planNo = planNo;
		this.priceNo = priceNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PLAN_NO", nullable = false, length = 10)
	public String getPlanNo() {
		return this.planNo;
	}

	public void setPlanNo(String planNo) {
		this.planNo = planNo;
	}

	@Column(name = "PRICE_NO", nullable = false, length = 10)
	public String getPriceNo() {
		return this.priceNo;
	}

	public void setPriceNo(String priceNo) {
		this.priceNo = priceNo;
	}

}
