package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "tbl_plan", catalog = "tourismwork_db")
public class Plan implements java.io.Serializable {

	private String planNo;
	private Team team;
	private Line line;
	private Employee employee;
	private City city;
	private Date outDate;
	private String tourNo;
	private String tourNm;
	private Integer assignedUserId;
	private String paxkey;
	private Integer planPax;
	private Integer holdPax;
	private Integer buildMinPax;
	private char uniteStatus;
	private Integer pax2;
	private Integer pax3;
	private int pax;
	private Integer malePax;
	private Integer femalePax;
	private Integer childPax;
	private Integer leadPax;
	private String workflowId;
	private String recRmk;
	private Date plandate1;
	private Date plandate2;
	private Integer planDate3;
	private Integer planDate4;
	private Date passDate;
	private String otherKey1;
	private String messagebox;
	private Character favourable;
	private Character shareFlight;
	private Integer shareFlightId;
	private String priceNo;
	private Byte singleFlag;
	private Integer traitType;
	private Integer isEnter;
	private Date inDate;
	private String inCity;
	private String gpCity;
	private Integer dbrm;
	private Integer sgrm;
	private Integer adrm;
	private Integer day;
	private Integer paxday;
	private BigDecimal income;
	private BigDecimal cost;
	private BigDecimal blnrate;
	private BigDecimal camt03;
	private String airco;
	private BigDecimal aramt;
	private String tourKey;
	private Integer opuser1;
	private Date optime1;
	private Integer opuser2;
	private Date optime2;
	private String country;
	private String piccNo;
	private Integer ghdNum;
	private Date ghdDate;
	private String tourRmk;
	private Character tourDel;
	private String remarks;
	private Character invpntKey;
	private String visaNcode;
	private String visaNname;
	private Integer isNeedLeader;
	private BigDecimal dbamt;
	private BigDecimal cramt;
	private Character opKey;
	private Date crDate;
	private Character chkKey;
	private String chkIssue;
	private Integer chkUser;
	private Date chkDate;
	private Character invKey;
	private Integer invUser;
	private Date invDate;
	private Integer opuser;
	private Date optime;
	private Integer customerId;
	private Integer exemptPax;
	private BigDecimal amount;
	private BigDecimal costAmount;
	private char opAccount;
	private char opRefactor;
	private Character frChecked;
	private Integer frUser;
	private Date frDate;
	private BigDecimal extCost;
	private String extCostNote;
	private BigDecimal tourAmount;

	public Plan() {
	}

	public Plan(String planNo, Line line, Date outDate, char uniteStatus,
			int pax, Date plandate1, Date optime, BigDecimal costAmount,
			char opAccount, char opRefactor) {
		this.planNo = planNo;
		this.line = line;
		this.outDate = outDate;
		this.uniteStatus = uniteStatus;
		this.pax = pax;
		this.plandate1 = plandate1;
		this.optime = optime;
		this.costAmount = costAmount;
		this.opAccount = opAccount;
		this.opRefactor = opRefactor;
	}

	public Plan(String planNo, Team team, Line line, Employee employee,
			City city, Date outDate, String tourNo, String tourNm,
			Integer assignedUserId, String paxkey, Integer planPax,
			Integer holdPax, Integer buildMinPax, char uniteStatus,
			Integer pax2, Integer pax3, int pax, Integer malePax,
			Integer femalePax, Integer childPax, Integer leadPax,
			String workflowId, String recRmk, Date plandate1, Date plandate2,
			Integer planDate3, Integer planDate4, Date passDate,
			String otherKey1, String messagebox, Character favourable,
			Character shareFlight, Integer shareFlightId, String priceNo,
			Byte singleFlag, Integer traitType, Integer isEnter, Date inDate,
			String inCity, String gpCity, Integer dbrm, Integer sgrm,
			Integer adrm, Integer day, Integer paxday, BigDecimal income,
			BigDecimal cost, BigDecimal blnrate, BigDecimal camt03,
			String airco, BigDecimal aramt, String tourKey, Integer opuser1,
			Date optime1, Integer opuser2, Date optime2, String country,
			String piccNo, Integer ghdNum, Date ghdDate, String tourRmk,
			Character tourDel, String remarks, Character invpntKey,
			String visaNcode, String visaNname, Integer isNeedLeader,
			BigDecimal dbamt, BigDecimal cramt, Character opKey, Date crDate,
			Character chkKey, String chkIssue, Integer chkUser, Date chkDate,
			Character invKey, Integer invUser, Date invDate, Integer opuser,
			Date optime, Integer customerId, Integer exemptPax,
			BigDecimal amount, BigDecimal costAmount, char opAccount,
			char opRefactor, Character frChecked, Integer frUser, Date frDate,
			BigDecimal extCost, String extCostNote, BigDecimal tourAmount) {
		this.planNo = planNo;
		this.team = team;
		this.line = line;
		this.employee = employee;
		this.city = city;
		this.outDate = outDate;
		this.tourNo = tourNo;
		this.tourNm = tourNm;
		this.assignedUserId = assignedUserId;
		this.paxkey = paxkey;
		this.planPax = planPax;
		this.holdPax = holdPax;
		this.buildMinPax = buildMinPax;
		this.uniteStatus = uniteStatus;
		this.pax2 = pax2;
		this.pax3 = pax3;
		this.pax = pax;
		this.malePax = malePax;
		this.femalePax = femalePax;
		this.childPax = childPax;
		this.leadPax = leadPax;
		this.workflowId = workflowId;
		this.recRmk = recRmk;
		this.plandate1 = plandate1;
		this.plandate2 = plandate2;
		this.planDate3 = planDate3;
		this.planDate4 = planDate4;
		this.passDate = passDate;
		this.otherKey1 = otherKey1;
		this.messagebox = messagebox;
		this.favourable = favourable;
		this.shareFlight = shareFlight;
		this.shareFlightId = shareFlightId;
		this.priceNo = priceNo;
		this.singleFlag = singleFlag;
		this.traitType = traitType;
		this.isEnter = isEnter;
		this.inDate = inDate;
		this.inCity = inCity;
		this.gpCity = gpCity;
		this.dbrm = dbrm;
		this.sgrm = sgrm;
		this.adrm = adrm;
		this.day = day;
		this.paxday = paxday;
		this.income = income;
		this.cost = cost;
		this.blnrate = blnrate;
		this.camt03 = camt03;
		this.airco = airco;
		this.aramt = aramt;
		this.tourKey = tourKey;
		this.opuser1 = opuser1;
		this.optime1 = optime1;
		this.opuser2 = opuser2;
		this.optime2 = optime2;
		this.country = country;
		this.piccNo = piccNo;
		this.ghdNum = ghdNum;
		this.ghdDate = ghdDate;
		this.tourRmk = tourRmk;
		this.tourDel = tourDel;
		this.remarks = remarks;
		this.invpntKey = invpntKey;
		this.visaNcode = visaNcode;
		this.visaNname = visaNname;
		this.isNeedLeader = isNeedLeader;
		this.dbamt = dbamt;
		this.cramt = cramt;
		this.opKey = opKey;
		this.crDate = crDate;
		this.chkKey = chkKey;
		this.chkIssue = chkIssue;
		this.chkUser = chkUser;
		this.chkDate = chkDate;
		this.invKey = invKey;
		this.invUser = invUser;
		this.invDate = invDate;
		this.opuser = opuser;
		this.optime = optime;
		this.customerId = customerId;
		this.exemptPax = exemptPax;
		this.amount = amount;
		this.costAmount = costAmount;
		this.opAccount = opAccount;
		this.opRefactor = opRefactor;
		this.frChecked = frChecked;
		this.frUser = frUser;
		this.frDate = frDate;
		this.extCost = extCost;
		this.extCostNote = extCostNote;
		this.tourAmount = tourAmount;
	}

	@Id
	@Column(name = "PLAN_NO", unique = true, nullable = false, length = 10)
	public String getPlanNo() {
		return this.planNo;
	}

	public void setPlanNo(String planNo) {
		this.planNo = planNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEAM_ID")
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LINE_NO", nullable = false)
	public Line getLine() {
		return this.line;
	}

	public void setLine(Line line) {
		this.line = line;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_USER")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OUT_CITY")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OUT_DATE", nullable = false, length = 19)
	public Date getOutDate() {
		return this.outDate;
	}

	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	@Column(name = "TOUR_NO", length = 100)
	public String getTourNo() {
		return this.tourNo;
	}

	public void setTourNo(String tourNo) {
		this.tourNo = tourNo;
	}

	@Column(name = "TOUR_NM", length = 100)
	public String getTourNm() {
		return this.tourNm;
	}

	public void setTourNm(String tourNm) {
		this.tourNm = tourNm;
	}

	@Column(name = "ASSIGNED_USER_ID")
	public Integer getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(Integer assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	@Column(name = "PAXKEY", length = 1)
	public String getPaxkey() {
		return this.paxkey;
	}

	public void setPaxkey(String paxkey) {
		this.paxkey = paxkey;
	}

	@Column(name = "PLAN_PAX")
	public Integer getPlanPax() {
		return this.planPax;
	}

	public void setPlanPax(Integer planPax) {
		this.planPax = planPax;
	}

	@Column(name = "HOLD_PAX")
	public Integer getHoldPax() {
		return this.holdPax;
	}

	public void setHoldPax(Integer holdPax) {
		this.holdPax = holdPax;
	}

	@Column(name = "BUILD_MIN_PAX")
	public Integer getBuildMinPax() {
		return this.buildMinPax;
	}

	public void setBuildMinPax(Integer buildMinPax) {
		this.buildMinPax = buildMinPax;
	}

	@Column(name = "UNITE_STATUS", nullable = false, length = 1)
	public char getUniteStatus() {
		return this.uniteStatus;
	}

	public void setUniteStatus(char uniteStatus) {
		this.uniteStatus = uniteStatus;
	}

	@Column(name = "PAX2")
	public Integer getPax2() {
		return this.pax2;
	}

	public void setPax2(Integer pax2) {
		this.pax2 = pax2;
	}

	@Column(name = "PAX3")
	public Integer getPax3() {
		return this.pax3;
	}

	public void setPax3(Integer pax3) {
		this.pax3 = pax3;
	}

	@Column(name = "PAX", nullable = false)
	public int getPax() {
		return this.pax;
	}

	public void setPax(int pax) {
		this.pax = pax;
	}

	@Column(name = "MALE_PAX")
	public Integer getMalePax() {
		return this.malePax;
	}

	public void setMalePax(Integer malePax) {
		this.malePax = malePax;
	}

	@Column(name = "FEMALE_PAX")
	public Integer getFemalePax() {
		return this.femalePax;
	}

	public void setFemalePax(Integer femalePax) {
		this.femalePax = femalePax;
	}

	@Column(name = "CHILD_PAX")
	public Integer getChildPax() {
		return this.childPax;
	}

	public void setChildPax(Integer childPax) {
		this.childPax = childPax;
	}

	@Column(name = "LEAD_PAX")
	public Integer getLeadPax() {
		return this.leadPax;
	}

	public void setLeadPax(Integer leadPax) {
		this.leadPax = leadPax;
	}

	@Column(name = "WORKFLOW_ID")
	public String getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(String workflowId) {
		this.workflowId = workflowId;
	}

	@Column(name = "REC_RMK", length = 60)
	public String getRecRmk() {
		return this.recRmk;
	}

	public void setRecRmk(String recRmk) {
		this.recRmk = recRmk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PLANDATE1", nullable = false, length = 19)
	public Date getPlandate1() {
		return this.plandate1;
	}

	public void setPlandate1(Date plandate1) {
		this.plandate1 = plandate1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PLANDATE2", length = 19)
	public Date getPlandate2() {
		return this.plandate2;
	}

	public void setPlandate2(Date plandate2) {
		this.plandate2 = plandate2;
	}

	@Column(name = "PLAN_DATE3")
	public Integer getPlanDate3() {
		return this.planDate3;
	}

	public void setPlanDate3(Integer planDate3) {
		this.planDate3 = planDate3;
	}

	@Column(name = "PLAN_DATE4")
	public Integer getPlanDate4() {
		return this.planDate4;
	}

	public void setPlanDate4(Integer planDate4) {
		this.planDate4 = planDate4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PASS_DATE", length = 19)
	public Date getPassDate() {
		return this.passDate;
	}

	public void setPassDate(Date passDate) {
		this.passDate = passDate;
	}

	@Column(name = "OTHER_KEY1", length = 1)
	public String getOtherKey1() {
		return this.otherKey1;
	}

	public void setOtherKey1(String otherKey1) {
		this.otherKey1 = otherKey1;
	}

	@Column(name = "MESSAGEBOX", length = 500)
	public String getMessagebox() {
		return this.messagebox;
	}

	public void setMessagebox(String messagebox) {
		this.messagebox = messagebox;
	}

	@Column(name = "FAVOURABLE", length = 1)
	public Character getFavourable() {
		return this.favourable;
	}

	public void setFavourable(Character favourable) {
		this.favourable = favourable;
	}

	@Column(name = "SHARE_FLIGHT", length = 1)
	public Character getShareFlight() {
		return this.shareFlight;
	}

	public void setShareFlight(Character shareFlight) {
		this.shareFlight = shareFlight;
	}

	@Column(name = "SHARE_FLIGHT_ID")
	public Integer getShareFlightId() {
		return this.shareFlightId;
	}

	public void setShareFlightId(Integer shareFlightId) {
		this.shareFlightId = shareFlightId;
	}

	@Column(name = "PRICE_NO", length = 10)
	public String getPriceNo() {
		return this.priceNo;
	}

	public void setPriceNo(String priceNo) {
		this.priceNo = priceNo;
	}

	@Column(name = "SINGLE_FLAG")
	public Byte getSingleFlag() {
		return this.singleFlag;
	}

	public void setSingleFlag(Byte singleFlag) {
		this.singleFlag = singleFlag;
	}

	@Column(name = "TRAIT_TYPE")
	public Integer getTraitType() {
		return this.traitType;
	}

	public void setTraitType(Integer traitType) {
		this.traitType = traitType;
	}

	@Column(name = "IS_ENTER")
	public Integer getIsEnter() {
		return this.isEnter;
	}

	public void setIsEnter(Integer isEnter) {
		this.isEnter = isEnter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IN_DATE", length = 19)
	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	@Column(name = "IN_CITY", length = 4)
	public String getInCity() {
		return this.inCity;
	}

	public void setInCity(String inCity) {
		this.inCity = inCity;
	}

	@Column(name = "GP_CITY", length = 4)
	public String getGpCity() {
		return this.gpCity;
	}

	public void setGpCity(String gpCity) {
		this.gpCity = gpCity;
	}

	@Column(name = "DBRM")
	public Integer getDbrm() {
		return this.dbrm;
	}

	public void setDbrm(Integer dbrm) {
		this.dbrm = dbrm;
	}

	@Column(name = "SGRM")
	public Integer getSgrm() {
		return this.sgrm;
	}

	public void setSgrm(Integer sgrm) {
		this.sgrm = sgrm;
	}

	@Column(name = "ADRM")
	public Integer getAdrm() {
		return this.adrm;
	}

	public void setAdrm(Integer adrm) {
		this.adrm = adrm;
	}

	@Column(name = "DAY")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "PAXDAY")
	public Integer getPaxday() {
		return this.paxday;
	}

	public void setPaxday(Integer paxday) {
		this.paxday = paxday;
	}

	@Column(name = "INCOME", precision = 10)
	public BigDecimal getIncome() {
		return this.income;
	}

	public void setIncome(BigDecimal income) {
		this.income = income;
	}

	@Column(name = "COST", precision = 10)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "BLNRATE", precision = 6)
	public BigDecimal getBlnrate() {
		return this.blnrate;
	}

	public void setBlnrate(BigDecimal blnrate) {
		this.blnrate = blnrate;
	}

	@Column(name = "CAMT03", precision = 10)
	public BigDecimal getCamt03() {
		return this.camt03;
	}

	public void setCamt03(BigDecimal camt03) {
		this.camt03 = camt03;
	}

	@Column(name = "AIRCO", length = 2)
	public String getAirco() {
		return this.airco;
	}

	public void setAirco(String airco) {
		this.airco = airco;
	}

	@Column(name = "ARAMT", precision = 10)
	public BigDecimal getAramt() {
		return this.aramt;
	}

	public void setAramt(BigDecimal aramt) {
		this.aramt = aramt;
	}

	@Column(name = "TOUR_KEY", length = 1)
	public String getTourKey() {
		return this.tourKey;
	}

	public void setTourKey(String tourKey) {
		this.tourKey = tourKey;
	}

	@Column(name = "OPUSER1")
	public Integer getOpuser1() {
		return this.opuser1;
	}

	public void setOpuser1(Integer opuser1) {
		this.opuser1 = opuser1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPTIME1", length = 19)
	public Date getOptime1() {
		return this.optime1;
	}

	public void setOptime1(Date optime1) {
		this.optime1 = optime1;
	}

	@Column(name = "OPUSER2")
	public Integer getOpuser2() {
		return this.opuser2;
	}

	public void setOpuser2(Integer opuser2) {
		this.opuser2 = opuser2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPTIME2", length = 19)
	public Date getOptime2() {
		return this.optime2;
	}

	public void setOptime2(Date optime2) {
		this.optime2 = optime2;
	}

	@Column(name = "COUNTRY", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "PICC_NO", length = 12)
	public String getPiccNo() {
		return this.piccNo;
	}

	public void setPiccNo(String piccNo) {
		this.piccNo = piccNo;
	}

	@Column(name = "GHD_NUM")
	public Integer getGhdNum() {
		return this.ghdNum;
	}

	public void setGhdNum(Integer ghdNum) {
		this.ghdNum = ghdNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GHD_DATE", length = 19)
	public Date getGhdDate() {
		return this.ghdDate;
	}

	public void setGhdDate(Date ghdDate) {
		this.ghdDate = ghdDate;
	}

	@Column(name = "TOUR_RMK", length = 40)
	public String getTourRmk() {
		return this.tourRmk;
	}

	public void setTourRmk(String tourRmk) {
		this.tourRmk = tourRmk;
	}

	@Column(name = "TOUR_DEL", length = 1)
	public Character getTourDel() {
		return this.tourDel;
	}

	public void setTourDel(Character tourDel) {
		this.tourDel = tourDel;
	}

	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "INVPNT_KEY", length = 1)
	public Character getInvpntKey() {
		return this.invpntKey;
	}

	public void setInvpntKey(Character invpntKey) {
		this.invpntKey = invpntKey;
	}

	@Column(name = "VISA_NCODE", length = 30)
	public String getVisaNcode() {
		return this.visaNcode;
	}

	public void setVisaNcode(String visaNcode) {
		this.visaNcode = visaNcode;
	}

	@Column(name = "VISA_NNAME", length = 100)
	public String getVisaNname() {
		return this.visaNname;
	}

	public void setVisaNname(String visaNname) {
		this.visaNname = visaNname;
	}

	@Column(name = "IS_NEED_LEADER")
	public Integer getIsNeedLeader() {
		return this.isNeedLeader;
	}

	public void setIsNeedLeader(Integer isNeedLeader) {
		this.isNeedLeader = isNeedLeader;
	}

	@Column(name = "DBAMT", precision = 18)
	public BigDecimal getDbamt() {
		return this.dbamt;
	}

	public void setDbamt(BigDecimal dbamt) {
		this.dbamt = dbamt;
	}

	@Column(name = "CRAMT", precision = 18)
	public BigDecimal getCramt() {
		return this.cramt;
	}

	public void setCramt(BigDecimal cramt) {
		this.cramt = cramt;
	}

	@Column(name = "OP_KEY", length = 1)
	public Character getOpKey() {
		return this.opKey;
	}

	public void setOpKey(Character opKey) {
		this.opKey = opKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DATE", length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Column(name = "CHK_KEY", length = 1)
	public Character getChkKey() {
		return this.chkKey;
	}

	public void setChkKey(Character chkKey) {
		this.chkKey = chkKey;
	}

	@Column(name = "CHK_ISSUE", length = 1)
	public String getChkIssue() {
		return this.chkIssue;
	}

	public void setChkIssue(String chkIssue) {
		this.chkIssue = chkIssue;
	}

	@Column(name = "CHK_USER")
	public Integer getChkUser() {
		return this.chkUser;
	}

	public void setChkUser(Integer chkUser) {
		this.chkUser = chkUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHK_DATE", length = 19)
	public Date getChkDate() {
		return this.chkDate;
	}

	public void setChkDate(Date chkDate) {
		this.chkDate = chkDate;
	}

	@Column(name = "INV_KEY", length = 1)
	public Character getInvKey() {
		return this.invKey;
	}

	public void setInvKey(Character invKey) {
		this.invKey = invKey;
	}

	@Column(name = "INV_USER")
	public Integer getInvUser() {
		return this.invUser;
	}

	public void setInvUser(Integer invUser) {
		this.invUser = invUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DATE", length = 19)
	public Date getInvDate() {
		return this.invDate;
	}

	public void setInvDate(Date invDate) {
		this.invDate = invDate;
	}

	@Column(name = "OPUSER")
	public Integer getOpuser() {
		return this.opuser;
	}

	public void setOpuser(Integer opuser) {
		this.opuser = opuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPTIME", nullable = false, length = 19)
	public Date getOptime() {
		return this.optime;
	}

	public void setOptime(Date optime) {
		this.optime = optime;
	}

	@Column(name = "CUSTOMER_ID")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "EXEMPT_PAX")
	public Integer getExemptPax() {
		return this.exemptPax;
	}

	public void setExemptPax(Integer exemptPax) {
		this.exemptPax = exemptPax;
	}

	@Column(name = "AMOUNT", precision = 18)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "COST_AMOUNT", nullable = false, precision = 18)
	public BigDecimal getCostAmount() {
		return this.costAmount;
	}

	public void setCostAmount(BigDecimal costAmount) {
		this.costAmount = costAmount;
	}

	@Column(name = "OP_ACCOUNT", nullable = false, length = 1)
	public char getOpAccount() {
		return this.opAccount;
	}

	public void setOpAccount(char opAccount) {
		this.opAccount = opAccount;
	}

	@Column(name = "OP_REFACTOR", nullable = false, length = 1)
	public char getOpRefactor() {
		return this.opRefactor;
	}

	public void setOpRefactor(char opRefactor) {
		this.opRefactor = opRefactor;
	}

	@Column(name = "FR_CHECKED", length = 1)
	public Character getFrChecked() {
		return this.frChecked;
	}

	public void setFrChecked(Character frChecked) {
		this.frChecked = frChecked;
	}

	@Column(name = "FR_USER")
	public Integer getFrUser() {
		return this.frUser;
	}

	public void setFrUser(Integer frUser) {
		this.frUser = frUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FR_DATE", length = 19)
	public Date getFrDate() {
		return this.frDate;
	}

	public void setFrDate(Date frDate) {
		this.frDate = frDate;
	}

	@Column(name = "EXT_COST", precision = 10)
	public BigDecimal getExtCost() {
		return this.extCost;
	}

	public void setExtCost(BigDecimal extCost) {
		this.extCost = extCost;
	}

	@Column(name = "EXT_COST_NOTE", length = 200)
	public String getExtCostNote() {
		return this.extCostNote;
	}

	public void setExtCostNote(String extCostNote) {
		this.extCostNote = extCostNote;
	}

	@Column(name = "TOUR_AMOUNT", precision = 16)
	public BigDecimal getTourAmount() {
		return this.tourAmount;
	}

	public void setTourAmount(BigDecimal tourAmount) {
		this.tourAmount = tourAmount;
	}

}
