package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductTmpl generated by hbm2java
 */
@Entity
@Table(name = "tbl_product_tmpl", catalog = "tourismwork_db")
public class ProductTmpl implements java.io.Serializable {

	private Integer id;
	private Integer teamId;
	private int itemId;
	private String type;
	private String destCode;
	private String subject;
	private String content;
	private Integer sortOrder;
	private Integer include;

	public ProductTmpl() {
	}

	public ProductTmpl(int itemId, String type) {
		this.itemId = itemId;
		this.type = type;
	}

	public ProductTmpl(Integer teamId, int itemId, String type,
			String destCode, String subject, String content, Integer sortOrder,
			Integer include) {
		this.teamId = teamId;
		this.itemId = itemId;
		this.type = type;
		this.destCode = destCode;
		this.subject = subject;
		this.content = content;
		this.sortOrder = sortOrder;
		this.include = include;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TEAM_ID")
	public Integer getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	@Column(name = "ITEM_ID", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "TYPE", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "DEST_CODE", length = 20)
	public String getDestCode() {
		return this.destCode;
	}

	public void setDestCode(String destCode) {
		this.destCode = destCode;
	}

	@Column(name = "SUBJECT", length = 50)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "CONTENT", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "SORT_ORDER")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "INCLUDE")
	public Integer getInclude() {
		return this.include;
	}

	public void setInclude(Integer include) {
		this.include = include;
	}

}
