package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "tbl_province", catalog = "tourismwork_db")
public class Province implements java.io.Serializable {

	private String code;
	private String cnName;
	private String enName;
	private String country;

	public Province() {
	}

	public Province(String code, String cnName) {
		this.code = code;
		this.cnName = cnName;
	}

	public Province(String code, String cnName, String enName, String country) {
		this.code = code;
		this.cnName = cnName;
		this.enName = enName;
		this.country = country;
	}

	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CN_NAME", nullable = false, length = 20)
	public String getCnName() {
		return this.cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	@Column(name = "EN_NAME", length = 30)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "COUNTRY", length = 3)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
