package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name = "tbl_sequence", catalog = "tourismwork_db")
public class Sequence implements java.io.Serializable {

	private SequenceId id;
	private Integer groupId;
	private Character regPlcd;
	private Integer cptno;

	public Sequence() {
	}

	public Sequence(SequenceId id) {
		this.id = id;
	}

	public Sequence(SequenceId id, Integer groupId, Character regPlcd,
			Integer cptno) {
		this.id = id;
		this.groupId = groupId;
		this.regPlcd = regPlcd;
		this.cptno = cptno;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rectype", column = @Column(name = "RECTYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "year", column = @Column(name = "YEAR", nullable = false, length = 4)),
			@AttributeOverride(name = "month", column = @Column(name = "MONTH", nullable = false, length = 2)) })
	public SequenceId getId() {
		return this.id;
	}

	public void setId(SequenceId id) {
		this.id = id;
	}

	@Column(name = "GROUP_ID")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "REG_PLCD", length = 1)
	public Character getRegPlcd() {
		return this.regPlcd;
	}

	public void setRegPlcd(Character regPlcd) {
		this.regPlcd = regPlcd;
	}

	@Column(name = "CPTNO")
	public Integer getCptno() {
		return this.cptno;
	}

	public void setCptno(Integer cptno) {
		this.cptno = cptno;
	}

}
