package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import com.opentravelsoft.hmodel.TblLineSights;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sight generated by hbm2java
 */
@Entity
@Table(name = "tbl_sight", catalog = "tourismwork_db")
public class Sight implements java.io.Serializable {

	private String sightNo;
	private Country country;
	private District district;
	private String cnName;
	private String enName;
	private String cnNote;
	private String enNote;
	private String mapAddress1;
	private String mapAddress2;
	private String sightType;
	private Double clickNumber;
	private Date clickDate;
	private Character districtKey;
	private String duchy;
	private byte isDelete;
	private Set<TblLineSights> tblLineSightses = new HashSet<TblLineSights>(0);

	public Sight() {
	}

	public Sight(String sightNo, Country country, byte isDelete) {
		this.sightNo = sightNo;
		this.country = country;
		this.isDelete = isDelete;
	}

	public Sight(String sightNo, Country country, District district,
			String cnName, String enName, String cnNote, String enNote,
			String mapAddress1, String mapAddress2, String sightType,
			Double clickNumber, Date clickDate, Character districtKey,
			String duchy, byte isDelete, Set<TblLineSights> tblLineSightses) {
		this.sightNo = sightNo;
		this.country = country;
		this.district = district;
		this.cnName = cnName;
		this.enName = enName;
		this.cnNote = cnNote;
		this.enNote = enNote;
		this.mapAddress1 = mapAddress1;
		this.mapAddress2 = mapAddress2;
		this.sightType = sightType;
		this.clickNumber = clickNumber;
		this.clickDate = clickDate;
		this.districtKey = districtKey;
		this.duchy = duchy;
		this.isDelete = isDelete;
		this.tblLineSightses = tblLineSightses;
	}

	@Id
	@Column(name = "SIGHT_NO", unique = true, nullable = false, length = 10)
	public String getSightNo() {
		return this.sightNo;
	}

	public void setSightNo(String sightNo) {
		this.sightNo = sightNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRICT_NO")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@Column(name = "CN_NAME", length = 30)
	public String getCnName() {
		return this.cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	@Column(name = "EN_NAME", length = 60)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "CN_NOTE", length = 1500)
	public String getCnNote() {
		return this.cnNote;
	}

	public void setCnNote(String cnNote) {
		this.cnNote = cnNote;
	}

	@Column(name = "EN_NOTE", length = 1500)
	public String getEnNote() {
		return this.enNote;
	}

	public void setEnNote(String enNote) {
		this.enNote = enNote;
	}

	@Column(name = "MAP_ADDRESS1", length = 50)
	public String getMapAddress1() {
		return this.mapAddress1;
	}

	public void setMapAddress1(String mapAddress1) {
		this.mapAddress1 = mapAddress1;
	}

	@Column(name = "MAP_ADDRESS2", length = 50)
	public String getMapAddress2() {
		return this.mapAddress2;
	}

	public void setMapAddress2(String mapAddress2) {
		this.mapAddress2 = mapAddress2;
	}

	@Column(name = "SIGHT_TYPE", length = 10)
	public String getSightType() {
		return this.sightType;
	}

	public void setSightType(String sightType) {
		this.sightType = sightType;
	}

	@Column(name = "CLICK_NUMBER", precision = 22, scale = 0)
	public Double getClickNumber() {
		return this.clickNumber;
	}

	public void setClickNumber(Double clickNumber) {
		this.clickNumber = clickNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CLICK_DATE", length = 19)
	public Date getClickDate() {
		return this.clickDate;
	}

	public void setClickDate(Date clickDate) {
		this.clickDate = clickDate;
	}

	@Column(name = "DISTRICT_KEY", length = 1)
	public Character getDistrictKey() {
		return this.districtKey;
	}

	public void setDistrictKey(Character districtKey) {
		this.districtKey = districtKey;
	}

	@Column(name = "DUCHY", length = 2)
	public String getDuchy() {
		return this.duchy;
	}

	public void setDuchy(String duchy) {
		this.duchy = duchy;
	}

	@Column(name = "IS_DELETE", nullable = false)
	public byte getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(byte isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sight")
	public Set<TblLineSights> getTblLineSightses() {
		return this.tblLineSightses;
	}

	public void setTblLineSightses(Set<TblLineSights> tblLineSightses) {
		this.tblLineSightses = tblLineSightses;
	}

}
