package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserPayOL generated by hbm2java
 */
@Entity
@Table(name = "tbl_userpayol", catalog = "tourismwork_db")
public class TblUserPayOL implements java.io.Serializable {

	private long payid;
	private String payername;
	private String payerphone;
	private String tourroute;
	private double payamount;
	private String remark;
	private Date paytime;

	public TblUserPayOL() {
	}

	public TblUserPayOL(long payid, String payername, String payerphone,
			String tourroute, double payamount) {
		this.payid = payid;
		this.payername = payername;
		this.payerphone = payerphone;
		this.tourroute = tourroute;
		this.payamount = payamount;
	}

	public TblUserPayOL(long payid, String payername, String payerphone,
			String tourroute, double payamount, String remark, Date paytime) {
		this.payid = payid;
		this.payername = payername;
		this.payerphone = payerphone;
		this.tourroute = tourroute;
		this.payamount = payamount;
		this.remark = remark;
		this.paytime = paytime;
	}

	@Id
	@Column(name = "PAYID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPayid() {
		return this.payid;
	}

	public void setPayid(long payid) {
		this.payid = payid;
	}

	@Column(name = "PAYERNAME", nullable = false, length = 50)
	public String getPayername() {
		return this.payername;
	}

	public void setPayername(String payername) {
		this.payername = payername;
	}

	@Column(name = "PAYERPHONE", nullable = false, length = 50)
	public String getPayerphone() {
		return this.payerphone;
	}

	public void setPayerphone(String payerphone) {
		this.payerphone = payerphone;
	}

	@Column(name = "TOURROUTE", nullable = false, length = 100)
	public String getTourroute() {
		return this.tourroute;
	}

	public void setTourroute(String tourroute) {
		this.tourroute = tourroute;
	}

	@Column(name = "PAYAMOUNT", nullable = false, precision = 22, scale = 0)
	public double getPayamount() {
		return this.payamount;
	}

	public void setPayamount(double payamount) {
		this.payamount = payamount;
	}

	@Column(name = "REMARK", length = 1000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYTIME", length = 19)
	public Date getPaytime() {
		return this.paytime;
	}

	public void setPaytime(Date paytime) {
		this.paytime = paytime;
	}

}
