package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TeamSupplier generated by hbm2java
 */
@Entity
@Table(name = "tbl_team_customer", catalog = "tourismwork_db")
public class TeamSupplier implements java.io.Serializable {

	private TeamSupplierId id;

	public TeamSupplier() {
	}

	public TeamSupplier(TeamSupplierId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", nullable = false)),
			@AttributeOverride(name = "teamId", column = @Column(name = "TEAM_ID", nullable = false)) })
	public TeamSupplierId getId() {
		return this.id;
	}

	public void setId(TeamSupplierId id) {
		this.id = id;
	}

}
