package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TourCost generated by hbm2java
 */
@Entity
@Table(name = "tbl_tour_cost", catalog = "tourismwork_db")
public class TourCost implements java.io.Serializable {

	private Integer acctId;
	private String planNo;
	private int customerId;
	private String costType;
	private String description;
	private BigDecimal unitPrice;
	private Integer count;
	private String unit;
	private String currency;
	private BigDecimal roe;
	private BigDecimal fcAmount;
	private BigDecimal amount;
	private BigDecimal payAmount;
	private char isMakePaper;
	private String frChecked;
	private Date created;
	private Integer createdby;

	public TourCost() {
	}

	public TourCost(String planNo, int customerId, char isMakePaper) {
		this.planNo = planNo;
		this.customerId = customerId;
		this.isMakePaper = isMakePaper;
	}

	public TourCost(String planNo, int customerId, String costType,
			String description, BigDecimal unitPrice, Integer count,
			String unit, String currency, BigDecimal roe, BigDecimal fcAmount,
			BigDecimal amount, BigDecimal payAmount, char isMakePaper,
			String frChecked, Date created, Integer createdby) {
		this.planNo = planNo;
		this.customerId = customerId;
		this.costType = costType;
		this.description = description;
		this.unitPrice = unitPrice;
		this.count = count;
		this.unit = unit;
		this.currency = currency;
		this.roe = roe;
		this.fcAmount = fcAmount;
		this.amount = amount;
		this.payAmount = payAmount;
		this.isMakePaper = isMakePaper;
		this.frChecked = frChecked;
		this.created = created;
		this.createdby = createdby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACCT_ID", unique = true, nullable = false)
	public Integer getAcctId() {
		return this.acctId;
	}

	public void setAcctId(Integer acctId) {
		this.acctId = acctId;
	}

	@Column(name = "PLAN_NO", nullable = false, length = 100)
	public String getPlanNo() {
		return this.planNo;
	}

	public void setPlanNo(String planNo) {
		this.planNo = planNo;
	}

	@Column(name = "CUSTOMER_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "COST_TYPE", length = 20)
	public String getCostType() {
		return this.costType;
	}

	public void setCostType(String costType) {
		this.costType = costType;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "UNIT_PRICE", precision = 9)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "COUNT")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "CURRENCY", length = 4)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "ROE", precision = 9, scale = 4)
	public BigDecimal getRoe() {
		return this.roe;
	}

	public void setRoe(BigDecimal roe) {
		this.roe = roe;
	}

	@Column(name = "FC_AMOUNT", precision = 9)
	public BigDecimal getFcAmount() {
		return this.fcAmount;
	}

	public void setFcAmount(BigDecimal fcAmount) {
		this.fcAmount = fcAmount;
	}

	@Column(name = "AMOUNT", precision = 9)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "PAY_AMOUNT", precision = 9)
	public BigDecimal getPayAmount() {
		return this.payAmount;
	}

	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}

	@Column(name = "IS_MAKE_PAPER", nullable = false, length = 1)
	public char getIsMakePaper() {
		return this.isMakePaper;
	}

	public void setIsMakePaper(char isMakePaper) {
		this.isMakePaper = isMakePaper;
	}

	@Column(name = "FR_CHECKED", length = 1)
	public String getFrChecked() {
		return this.frChecked;
	}

	public void setFrChecked(String frChecked) {
		this.frChecked = frChecked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "CREATEDBY")
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

}
