package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tourist generated by hbm2java
 */
@Entity
@Table(name = "tbl_tourist", catalog = "tourismwork_db")
public class Tourist implements java.io.Serializable {

	private String nmno;
	private String nameNo;
	private char recType;
	private String name;
	private String name2;
	private Character cardty;
	private String card;
	private Character sex;
	private Date birthday;
	private String bthplc;
	private String mobile;
	private Character hzKey;
	private String hzzl;
	private String hzno;
	private Date hzdate1;
	private String hzadd;
	private Date hzrang;
	private BigDecimal amt01;
	private BigDecimal amt02;
	private BigDecimal amt03;
	private BigDecimal amt04;
	private Character vipkey;
	private String remark;
	private Integer roomNo;
	private Integer paxnum;
	private String roomKey;
	private Character roomKey1;
	private char del;
	private String opuser;
	private Date opdate;
	private Character tourKey;
	private Character leadKey;
	private String visaKey;
	private Integer rmNum;
	private BigDecimal price;
	private Integer num1;
	private String familyName;
	private String givenName;
	private Character nameKey;
	private String nation;
	private BigDecimal areaAmt;
	private String pvia;
	private BigDecimal expAmt;
	private String expNote;
	private String premCode;
	private BigDecimal premExpend;
	private Character premPrinted;
	private String passRmk;
	private String pactNo;
	private String invoiceNo;

	public Tourist() {
	}

	public Tourist(String nmno, String nameNo, char recType, String name,
			char del, Date opdate) {
		this.nmno = nmno;
		this.nameNo = nameNo;
		this.recType = recType;
		this.name = name;
		this.del = del;
		this.opdate = opdate;
	}

	public Tourist(String nmno, String nameNo, char recType, String name,
			String name2, Character cardty, String card, Character sex,
			Date birthday, String bthplc, String mobile, Character hzKey,
			String hzzl, String hzno, Date hzdate1, String hzadd, Date hzrang,
			BigDecimal amt01, BigDecimal amt02, BigDecimal amt03,
			BigDecimal amt04, Character vipkey, String remark, Integer roomNo,
			Integer paxnum, String roomKey, Character roomKey1, char del,
			String opuser, Date opdate, Character tourKey, Character leadKey,
			String visaKey, Integer rmNum, BigDecimal price, Integer num1,
			String familyName, String givenName, Character nameKey,
			String nation, BigDecimal areaAmt, String pvia, BigDecimal expAmt,
			String expNote, String premCode, BigDecimal premExpend,
			Character premPrinted, String passRmk, String pactNo,
			String invoiceNo) {
		this.nmno = nmno;
		this.nameNo = nameNo;
		this.recType = recType;
		this.name = name;
		this.name2 = name2;
		this.cardty = cardty;
		this.card = card;
		this.sex = sex;
		this.birthday = birthday;
		this.bthplc = bthplc;
		this.mobile = mobile;
		this.hzKey = hzKey;
		this.hzzl = hzzl;
		this.hzno = hzno;
		this.hzdate1 = hzdate1;
		this.hzadd = hzadd;
		this.hzrang = hzrang;
		this.amt01 = amt01;
		this.amt02 = amt02;
		this.amt03 = amt03;
		this.amt04 = amt04;
		this.vipkey = vipkey;
		this.remark = remark;
		this.roomNo = roomNo;
		this.paxnum = paxnum;
		this.roomKey = roomKey;
		this.roomKey1 = roomKey1;
		this.del = del;
		this.opuser = opuser;
		this.opdate = opdate;
		this.tourKey = tourKey;
		this.leadKey = leadKey;
		this.visaKey = visaKey;
		this.rmNum = rmNum;
		this.price = price;
		this.num1 = num1;
		this.familyName = familyName;
		this.givenName = givenName;
		this.nameKey = nameKey;
		this.nation = nation;
		this.areaAmt = areaAmt;
		this.pvia = pvia;
		this.expAmt = expAmt;
		this.expNote = expNote;
		this.premCode = premCode;
		this.premExpend = premExpend;
		this.premPrinted = premPrinted;
		this.passRmk = passRmk;
		this.pactNo = pactNo;
		this.invoiceNo = invoiceNo;
	}

	@Id
	@Column(name = "NMNO", unique = true, nullable = false, length = 10)
	public String getNmno() {
		return this.nmno;
	}

	public void setNmno(String nmno) {
		this.nmno = nmno;
	}

	@Column(name = "NAME_NO", nullable = false, length = 10)
	public String getNameNo() {
		return this.nameNo;
	}

	public void setNameNo(String nameNo) {
		this.nameNo = nameNo;
	}

	@Column(name = "REC_TYPE", nullable = false, length = 1)
	public char getRecType() {
		return this.recType;
	}

	public void setRecType(char recType) {
		this.recType = recType;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "NAME2", length = 80)
	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	@Column(name = "CARDTY", length = 1)
	public Character getCardty() {
		return this.cardty;
	}

	public void setCardty(Character cardty) {
		this.cardty = cardty;
	}

	@Column(name = "CARD", length = 18)
	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	@Column(name = "SEX", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIRTHDAY", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "BTHPLC", length = 2)
	public String getBthplc() {
		return this.bthplc;
	}

	public void setBthplc(String bthplc) {
		this.bthplc = bthplc;
	}

	@Column(name = "MOBILE", length = 30)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "HZ_KEY", length = 1)
	public Character getHzKey() {
		return this.hzKey;
	}

	public void setHzKey(Character hzKey) {
		this.hzKey = hzKey;
	}

	@Column(name = "HZZL", length = 2)
	public String getHzzl() {
		return this.hzzl;
	}

	public void setHzzl(String hzzl) {
		this.hzzl = hzzl;
	}

	@Column(name = "HZNO", length = 12)
	public String getHzno() {
		return this.hzno;
	}

	public void setHzno(String hzno) {
		this.hzno = hzno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HZDATE1", length = 19)
	public Date getHzdate1() {
		return this.hzdate1;
	}

	public void setHzdate1(Date hzdate1) {
		this.hzdate1 = hzdate1;
	}

	@Column(name = "HZADD", length = 3)
	public String getHzadd() {
		return this.hzadd;
	}

	public void setHzadd(String hzadd) {
		this.hzadd = hzadd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HZRANG", length = 19)
	public Date getHzrang() {
		return this.hzrang;
	}

	public void setHzrang(Date hzrang) {
		this.hzrang = hzrang;
	}

	@Column(name = "AMT01", precision = 8)
	public BigDecimal getAmt01() {
		return this.amt01;
	}

	public void setAmt01(BigDecimal amt01) {
		this.amt01 = amt01;
	}

	@Column(name = "AMT02", precision = 8)
	public BigDecimal getAmt02() {
		return this.amt02;
	}

	public void setAmt02(BigDecimal amt02) {
		this.amt02 = amt02;
	}

	@Column(name = "AMT03", precision = 8)
	public BigDecimal getAmt03() {
		return this.amt03;
	}

	public void setAmt03(BigDecimal amt03) {
		this.amt03 = amt03;
	}

	@Column(name = "AMT04", precision = 8)
	public BigDecimal getAmt04() {
		return this.amt04;
	}

	public void setAmt04(BigDecimal amt04) {
		this.amt04 = amt04;
	}

	@Column(name = "VIPKEY", length = 1)
	public Character getVipkey() {
		return this.vipkey;
	}

	public void setVipkey(Character vipkey) {
		this.vipkey = vipkey;
	}

	@Column(name = "REMARK", length = 40)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "ROOM_NO")
	public Integer getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(Integer roomNo) {
		this.roomNo = roomNo;
	}

	@Column(name = "PAXNUM")
	public Integer getPaxnum() {
		return this.paxnum;
	}

	public void setPaxnum(Integer paxnum) {
		this.paxnum = paxnum;
	}

	@Column(name = "ROOM_KEY", length = 2)
	public String getRoomKey() {
		return this.roomKey;
	}

	public void setRoomKey(String roomKey) {
		this.roomKey = roomKey;
	}

	@Column(name = "ROOM_KEY1", length = 1)
	public Character getRoomKey1() {
		return this.roomKey1;
	}

	public void setRoomKey1(Character roomKey1) {
		this.roomKey1 = roomKey1;
	}

	@Column(name = "DEL", nullable = false, length = 1)
	public char getDel() {
		return this.del;
	}

	public void setDel(char del) {
		this.del = del;
	}

	@Column(name = "OPUSER", length = 4)
	public String getOpuser() {
		return this.opuser;
	}

	public void setOpuser(String opuser) {
		this.opuser = opuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPDATE", nullable = false, length = 19)
	public Date getOpdate() {
		return this.opdate;
	}

	public void setOpdate(Date opdate) {
		this.opdate = opdate;
	}

	@Column(name = "TOUR_KEY", length = 1)
	public Character getTourKey() {
		return this.tourKey;
	}

	public void setTourKey(Character tourKey) {
		this.tourKey = tourKey;
	}

	@Column(name = "LEAD_KEY", length = 1)
	public Character getLeadKey() {
		return this.leadKey;
	}

	public void setLeadKey(Character leadKey) {
		this.leadKey = leadKey;
	}

	@Column(name = "VISA_KEY", length = 10)
	public String getVisaKey() {
		return this.visaKey;
	}

	public void setVisaKey(String visaKey) {
		this.visaKey = visaKey;
	}

	@Column(name = "RM_NUM")
	public Integer getRmNum() {
		return this.rmNum;
	}

	public void setRmNum(Integer rmNum) {
		this.rmNum = rmNum;
	}

	@Column(name = "PRICE", precision = 8)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "NUM1")
	public Integer getNum1() {
		return this.num1;
	}

	public void setNum1(Integer num1) {
		this.num1 = num1;
	}

	@Column(name = "FAMILY_NAME", length = 20)
	public String getFamilyName() {
		return this.familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	@Column(name = "GIVEN_NAME", length = 20)
	public String getGivenName() {
		return this.givenName;
	}

	public void setGivenName(String givenName) {
		this.givenName = givenName;
	}

	@Column(name = "NAME_KEY", length = 1)
	public Character getNameKey() {
		return this.nameKey;
	}

	public void setNameKey(Character nameKey) {
		this.nameKey = nameKey;
	}

	@Column(name = "NATION", length = 3)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "AREA_AMT", precision = 8)
	public BigDecimal getAreaAmt() {
		return this.areaAmt;
	}

	public void setAreaAmt(BigDecimal areaAmt) {
		this.areaAmt = areaAmt;
	}

	@Column(name = "PVIA", length = 60)
	public String getPvia() {
		return this.pvia;
	}

	public void setPvia(String pvia) {
		this.pvia = pvia;
	}

	@Column(name = "EXP_AMT", precision = 11)
	public BigDecimal getExpAmt() {
		return this.expAmt;
	}

	public void setExpAmt(BigDecimal expAmt) {
		this.expAmt = expAmt;
	}

	@Column(name = "EXP_NOTE", length = 100)
	public String getExpNote() {
		return this.expNote;
	}

	public void setExpNote(String expNote) {
		this.expNote = expNote;
	}

	@Column(name = "PREM_CODE", length = 10)
	public String getPremCode() {
		return this.premCode;
	}

	public void setPremCode(String premCode) {
		this.premCode = premCode;
	}

	@Column(name = "PREM_EXPEND", precision = 5)
	public BigDecimal getPremExpend() {
		return this.premExpend;
	}

	public void setPremExpend(BigDecimal premExpend) {
		this.premExpend = premExpend;
	}

	@Column(name = "PREM_PRINTED", length = 1)
	public Character getPremPrinted() {
		return this.premPrinted;
	}

	public void setPremPrinted(Character premPrinted) {
		this.premPrinted = premPrinted;
	}

	@Column(name = "PASS_RMK", length = 60)
	public String getPassRmk() {
		return this.passRmk;
	}

	public void setPassRmk(String passRmk) {
		this.passRmk = passRmk;
	}

	@Column(name = "PACT_NO", length = 50)
	public String getPactNo() {
		return this.pactNo;
	}

	public void setPactNo(String pactNo) {
		this.pactNo = pactNo;
	}

	@Column(name = "INVOICE_NO", length = 50)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

}
