package com.opentravelsoft.entity;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisaHelp generated by hbm2java
 */
@Entity
@Table(name = "tbl_visa", catalog = "tourismwork_db")
public class VisaHelp implements java.io.Serializable {

	private String recNo;
	private String country;
	private String subject;
	private BigDecimal price1;
	private BigDecimal price2;
	private BigDecimal cost;
	private String unit;
	private Date SDate;
	private Date EDate;
	private String note;
	private Integer canQuick;
	private Character visaKind;
	private String stayDays;
	private String transactDays;
	private Integer isOpen;
	private Character opKey;
	private Integer opUser;
	private Date opDate;

	public VisaHelp() {
	}

	public VisaHelp(String recNo, Date opDate) {
		this.recNo = recNo;
		this.opDate = opDate;
	}

	public VisaHelp(String recNo, String country, String subject,
			BigDecimal price1, BigDecimal price2, BigDecimal cost, String unit,
			Date SDate, Date EDate, String note, Integer canQuick,
			Character visaKind, String stayDays, String transactDays,
			Integer isOpen, Character opKey, Integer opUser, Date opDate) {
		this.recNo = recNo;
		this.country = country;
		this.subject = subject;
		this.price1 = price1;
		this.price2 = price2;
		this.cost = cost;
		this.unit = unit;
		this.SDate = SDate;
		this.EDate = EDate;
		this.note = note;
		this.canQuick = canQuick;
		this.visaKind = visaKind;
		this.stayDays = stayDays;
		this.transactDays = transactDays;
		this.isOpen = isOpen;
		this.opKey = opKey;
		this.opUser = opUser;
		this.opDate = opDate;
	}

	@Id
	@Column(name = "REC_NO", unique = true, nullable = false, length = 10)
	public String getRecNo() {
		return this.recNo;
	}

	public void setRecNo(String recNo) {
		this.recNo = recNo;
	}

	@Column(name = "COUNTRY", length = 2)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "SUBJECT", length = 200)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "PRICE1", precision = 9)
	public BigDecimal getPrice1() {
		return this.price1;
	}

	public void setPrice1(BigDecimal price1) {
		this.price1 = price1;
	}

	@Column(name = "PRICE2", precision = 9)
	public BigDecimal getPrice2() {
		return this.price2;
	}

	public void setPrice2(BigDecimal price2) {
		this.price2 = price2;
	}

	@Column(name = "COST", precision = 9)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "UNIT", length = 16)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "S_DATE", length = 19)
	public Date getSDate() {
		return this.SDate;
	}

	public void setSDate(Date SDate) {
		this.SDate = SDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E_DATE", length = 19)
	public Date getEDate() {
		return this.EDate;
	}

	public void setEDate(Date EDate) {
		this.EDate = EDate;
	}

	@Column(name = "NOTE", length = 3000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "CAN_QUICK")
	public Integer getCanQuick() {
		return this.canQuick;
	}

	public void setCanQuick(Integer canQuick) {
		this.canQuick = canQuick;
	}

	@Column(name = "VISA_KIND", length = 1)
	public Character getVisaKind() {
		return this.visaKind;
	}

	public void setVisaKind(Character visaKind) {
		this.visaKind = visaKind;
	}

	@Column(name = "STAY_DAYS", length = 20)
	public String getStayDays() {
		return this.stayDays;
	}

	public void setStayDays(String stayDays) {
		this.stayDays = stayDays;
	}

	@Column(name = "TRANSACT_DAYS", length = 20)
	public String getTransactDays() {
		return this.transactDays;
	}

	public void setTransactDays(String transactDays) {
		this.transactDays = transactDays;
	}

	@Column(name = "IS_OPEN")
	public Integer getIsOpen() {
		return this.isOpen;
	}

	public void setIsOpen(Integer isOpen) {
		this.isOpen = isOpen;
	}

	@Column(name = "OP_KEY", length = 1)
	public Character getOpKey() {
		return this.opKey;
	}

	public void setOpKey(Character opKey) {
		this.opKey = opKey;
	}

	@Column(name = "OP_USER")
	public Integer getOpUser() {
		return this.opUser;
	}

	public void setOpUser(Integer opUser) {
		this.opUser = opUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OP_DATE", nullable = false, length = 19)
	public Date getOpDate() {
		return this.opDate;
	}

	public void setOpDate(Date opDate) {
		this.opDate = opDate;
	}

}
