package com.opentravelsoft.entity.vacation;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlightCyclePrice generated by hbm2java
 */
@Entity
@Table(name = "tbl_flightcycleprice", catalog = "tourismwork_db")
public class FlightCyclePrice implements java.io.Serializable {

	private String id;
	private byte week;
	private BigDecimal adultCost;
	private BigDecimal childCost;
	private BigDecimal adultExtendPrice;
	private BigDecimal childExtendPrice;
	private Date currentDate;
	private String flightGroupId;
	private boolean isDeleted;

	public FlightCyclePrice() {
	}

	public FlightCyclePrice(String id, byte week, BigDecimal adultCost,
			BigDecimal childCost, BigDecimal adultExtendPrice,
			BigDecimal childExtendPrice, Date currentDate,
			String flightGroupId, boolean isDeleted) {
		this.id = id;
		this.week = week;
		this.adultCost = adultCost;
		this.childCost = childCost;
		this.adultExtendPrice = adultExtendPrice;
		this.childExtendPrice = childExtendPrice;
		this.currentDate = currentDate;
		this.flightGroupId = flightGroupId;
		this.isDeleted = isDeleted;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Week", nullable = false)
	public byte getWeek() {
		return this.week;
	}

	public void setWeek(byte week) {
		this.week = week;
	}

	@Column(name = "AdultCost", nullable = false, precision = 9)
	public BigDecimal getAdultCost() {
		return this.adultCost;
	}

	public void setAdultCost(BigDecimal adultCost) {
		this.adultCost = adultCost;
	}

	@Column(name = "ChildCost", nullable = false, precision = 9)
	public BigDecimal getChildCost() {
		return this.childCost;
	}

	public void setChildCost(BigDecimal childCost) {
		this.childCost = childCost;
	}

	@Column(name = "AdultExtendPrice", nullable = false, precision = 7)
	public BigDecimal getAdultExtendPrice() {
		return this.adultExtendPrice;
	}

	public void setAdultExtendPrice(BigDecimal adultExtendPrice) {
		this.adultExtendPrice = adultExtendPrice;
	}

	@Column(name = "ChildExtendPrice", nullable = false, precision = 7)
	public BigDecimal getChildExtendPrice() {
		return this.childExtendPrice;
	}

	public void setChildExtendPrice(BigDecimal childExtendPrice) {
		this.childExtendPrice = childExtendPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CurrentDate", nullable = false, length = 19)
	public Date getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

	@Column(name = "FlightGroupID", nullable = false, length = 36)
	public String getFlightGroupId() {
		return this.flightGroupId;
	}

	public void setFlightGroupId(String flightGroupId) {
		this.flightGroupId = flightGroupId;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
