package com.opentravelsoft.entity.vacation;

// Generated 2012-5-9 8:27:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineTheme generated by hbm2java
 */
@Entity
@Table(name = "tbl_line_theme", catalog = "tourismwork_db")
public class LineTheme implements java.io.Serializable {

	private String code;
	private String cnName;
	private String enName;
	private String mapFile;

	public LineTheme() {
	}

	public LineTheme(String code) {
		this.code = code;
	}

	public LineTheme(String code, String cnName, String enName, String mapFile) {
		this.code = code;
		this.cnName = cnName;
		this.enName = enName;
		this.mapFile = mapFile;
	}

	@Id
	@Column(name = "CODE", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CN_NAME", length = 40)
	public String getCnName() {
		return this.cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	@Column(name = "EN_NAME", length = 80)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "MAP_FILE", length = 50)
	public String getMapFile() {
		return this.mapFile;
	}

	public void setMapFile(String mapFile) {
		this.mapFile = mapFile;
	}

}
